### PR TITLE
Fix typos in feelpp/feel subdir

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -S *.patch,*.diff,./benchmarks/benchmark,./feelpp/contrib -L alo,ba,boxs,conver,cylindre,espace,fonction,fonctions,indext,jumpt,mata,mor,nd,ned,ordert,parm,ser,sur,te,theses,transfert,ro,ue,whet`

### CODE REVIEW

**Comment by luzpaz** [comment]
Do you want me to rebase ?

**Comment by luzpaz** [comment]
Review was needed

**Comment by luzpaz** [comment]
Rebased

**Comment by luzpaz** [comment]
bump

**Review by prudhomm — APPROVED** [review]

**Pull request merged**
