### PR TITLE
Cpp17

### PR DESCRIPTION
**Pull request by prudhomm**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/feelpp/feelpp/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes?
- [x] Have you successfully run the Feel++ testsuite with your changes locally?
- [ ] Have you written Doxygen comments in your contribution ?

-----

Moving to C++17 language feature set, see #1282  for more details

### CODE REVIEW

**Comment by vincentchabannes** [comment]
@prudhomm It doesn't compile on atlas : 
```
[ 85%] Building CXX object feelpp/feel/CMakeFiles/feelpp.dir/feelts/timeset.cpp.o
In file included from /ssd/chabannes/Feelpp/work_cpp17/feelpp/feelpp/feel/feeldiscr/meshstructured.cpp:27:
In file included from /ssd/chabannes/Feelpp/work_cpp17/feelpp/feelpp/feel/../feel/feeldiscr/meshstructured.hpp:27:
In file included from /ssd/chabannes/Feelpp/work_cpp17/feelpp/feelpp/feel/../feel/feeldiscr/mesh.hpp:89:
In file included from /data/software/install/paraview/5.6.0-py3/gcc-6.4.0/openmpi-1.10.7/include/paraview-5.6/vtkTriangle.h:29:
/data/software/install/paraview/5.6.0-py3/gcc-6.4.0/openmpi-1.10.7/include/paraview-5.6/vtkMath.h:1514:15: error: no member named 'clamp' in namespace 'std'
  return std::clamp(value, min, max);
         ~~~~~^
In file included from /ssd/chabannes/Feelpp/work_cpp17/feelpp/feelpp/feel/feeldiscr/mesh.cpp:47:
In file included from /ssd/chabannes/Feelpp/work_cpp17/feelpp/feelpp/feel/../feel/feeldiscr/mesh.hpp:89:
In file included from /data/software/install/paraview/5.6.0-py3/gcc-6.4.0/openmpi-1.10.7/include/paraview-5.6/vtkTriangle.h:29:
/data/software/install/paraview/5.6.0-py3/gcc-6.4.0/openmpi-1.10.7/include/paraview-5.6/vtkMath.h:1514:15: error: no member named 'clamp' in namespace 'std'
  return std::clamp(value, min, max);
         ~~~~~^
In file included from /ssd/chabannes/Feelpp/work_cpp17/feelpp/feelpp/feel/feeldiscr/stencil.cpp:30:
In file included from /ssd/chabannes/Feelpp/work_cpp17/feelpp/feelpp/feel/../feel/feeldiscr/stencil.hpp:35:
In file included from /ssd/chabannes/Feelpp/work_cpp17/feelpp/feelpp/feel/../feel/feeldiscr/functionspace.hpp:91:
In file included from /ssd/chabannes/Feelpp/work_cpp17/feelpp/feelpp/feel/../feel/feeldiscr/mesh.hpp:89:
In file included from /data/software/install/paraview/5.6.0-py3/gcc-6.4.0/openmpi-1.10.7/include/paraview-5.6/vtkTriangle.h:29:
/data/software/install/paraview/5.6.0-py3/gcc-6.4.0/openmpi-1.10.7/include/paraview-5.6/vtkMath.h:1514:15: error: no member named 'clamp' in namespace 'std'
  return std::clamp(value, min, max);
         ~~~~~^
In file included from /ssd/chabannes/Feelpp/work_cpp17/feelpp/feelpp/feel/feeldiscr/mesh1.cpp:33:
In file included from /ssd/chabannes/Feelpp/work_cpp17/feelpp/feelpp/feel/../feel/feeldiscr/meshimpl.hpp:45:
In file included from /ssd/chabannes/Feelpp/work_cpp17/feelpp/feelpp/feel/../feel/feeldiscr/mesh.hpp:89:
In file included from /data/software/install/paraview/5.6.0-py3/gcc-6.4.0/openmpi-1.10.7/include/paraview-5.6/vtkTriangle.h:29:
/data/software/install/paraview/5.6.0-py3/gcc-6.4.0/openmpi-1.10.7/include/paraview-5.6/vtkMath.h:1514:15: error: no member named 'clamp' in namespace 'std'
  return std::clamp(value, min, max);
```

**Comment by prudhomm** [comment]
Any hope to get gcc7 or gcc 8 on atlas and have eg clang7 and or 8 depends on gcc 7/ 8?

**Comment by prudhomm** [comment]
Gcc 6 is indeed not an option for cpp17

**Comment by prudhomm** [comment]
As mentioned in #1282 gcc7 is the minimal version required. 
Considering the release history of gcc, we have 7 and 8 with minor releases , and gcc6 is a few years old now, I would think it is reasonable at some point to move forward

**Comment by vincentchabannes** [comment]
on atlas, it's probably possible to update to gcc7 but we need to recompile all software.  But it's also gcc6 at the mesocenter.  This upgrade can't apply soon.

**Comment by prudhomm** [comment]
I don't think you need to recompile any software except Feel++, there is a ABI after all.
the first thing is just to provide GCC8 say and CLANG7

**Comment by prudhomm** [comment]
also note that GCC6 is not supported by the GCC community anymore see https://gcc.gnu.org/
supported versions are: GCC 7, 8 and 9(in dev)

**Comment by vincentchabannes** [comment]
I have installed gcc8.3.0 and clang 7 on atlas, and now I have this error : 
```
[100%] Linking CXX executable feelpp_qs_laplacian_2d
../contrib/mongocxx/src/bsoncxx/libfeelpp_bsoncxx.so.3.1.1: undefined reference to `operator new(unsigned long, std::align_val_t)@CXXABI_1.3.11'
../contrib/mongocxx/src/bsoncxx/libfeelpp_bsoncxx.so.3.1.1: undefined reference to `operator delete(void*, std::align_val_t)@CXXABI_1.3.11'
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
feelpp/quickstart/CMakeFiles/feelpp_qs_laplacian_2d.dir/build.make:402: recipe for target 'feelpp/quickstart/feelpp_qs_laplacian_2d' failed
make[3]: *** [feelpp/quickstart/feelpp_qs_laplacian_2d] Error 1
```

**Comment by vincentchabannes** [comment]
it's ok with qs_laplacian_2d if I put `-DFEELPP_ENABLE_MONGOCXX=OFF` .

**Comment by prudhomm** [comment]
Is it possible to test on atlas

**Comment by prudhomm** [comment]
Is it possible to test on atlas?

**Comment by vincentchabannes** [comment]
yes, you just need to load the module llvm/7.0.1_gcc830.

The testsuite and the fluid toolbox are ok, only if we remove mongodb

**Comment by prudhomm** [comment]
@vincentchabannes I got the `c++14` culprit in contrib:
```
> find . -name "*.cmake" | xargs -Istr grep -H "std=c++14" str
./pybind11/tools/pybind11Tools.cmake:    check_cxx_compiler_flag("-std=c++14" HAS_CPP14_FLAG)
./pybind11/tools/pybind11Tools.cmake:      set(PYBIND11_CPP_STANDARD -std=c++14)
./pybind11/tools/pybind11Tools.cmake:      "C++ standard flag, e.g. -std=c++11, -std=c++14, /std:c++14.  Defaults to C++14 mode." FORCE)
```

**Comment by prudhomm** [comment]
I suggest to modify pybind11 to look for the Feel++ config `FEELPP_STD_CPP` and use it to setup the C++ standard. What do you think ?

**Comment by prudhomm** [comment]
something like `set(PYBIND11_CPP_STANDARD -std=c++${FEELPP_STD_CPP}` in `contrib/CMakeLists.txt`

**Comment by prudhomm** [comment]
@vincentchabannes now it is all good, pybind11 is configured with C++17 support (which makes sense) and cmake minimum requirement has been bumped up to 3.7.2

**Comment by vincentchabannes** [comment]
@prudhomm the issue with MongoDB seems fixed now

**Comment by prudhomm** [comment]
so what's the next step? 
we make a full build on atlas as well as in docker and if it is ok, merge?
is there something else?

**Comment by vincentchabannes** [comment]
seems also good at strasbourg mesocenter by loading the module `gcc/gcc-8` and using : 
```
 -DCMAKE_CXX_FLAGS="--gcc-toolchain=/usr/local/gcc/gcc-8.2.0/" 
```

**Pull request merged**
