### PR TITLE
fix geometry of thermal-fin

### PR DESCRIPTION
**Pull request by thomas-saigre**
add fins in layers and fix template
[ci skip]

- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/feelpp/feelpp/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes?
- [ ] Have you successfully run the Feel++ testsuite with your changes locally?
- [x] Have you written Doxygen comments in your contribution ?

-----

### CODE REVIEW

**Review by romainhild — APPROVED** [review]

**Comment by prudhomm** [comment]
is the application installed with the documentation ?
why in mor/toolbox-mor? 
I would suggest 
- toolboxes/generators/cases/thermal-fin -> geometry + cfg/json
no ?

also the generated geo file should contain

/cc @thomas-saigre @romainhild

**Comment by thomas-saigre** [comment]
@prudhomm I documented in https://github.com/feelpp/feelpp/blob/saigre/fix-thermal-fin/mor/toolbox-mor/thermal-fin/case_generator.adoc
I can move those files in the drectory `toolboxes/generators/cases/thermal-fin` if it make more sense than where it is now. I think I put it in `mor` becausethe case was build for this toolbox, but we can indeed use is with another toolbox

**Comment by prudhomm** [comment]
you generate the json file as well ?

**Comment by prudhomm** [comment]
we could be indeed interested in different physics, eg solid and fluid mechanics

**Comment by thomas-saigre** [comment]
> 
> 
> you generate the json file as well ?

Yes the json is part of the templates

**Comment by prudhomm** [comment]
the application could generate the json for different physics, in case of fluid mechanics the fin needs to be in a box

**Comment by prudhomm** [comment]
`feelpp_case_generator` should be renamed `feelpp_case_generator_thermal_fin`

**Pull request merged**
