### PR TITLE
Fix hdg_poisson application #1605

### PR DESCRIPTION
**Pull request by romainhild**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/feelpp/feelpp/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes?
- [ ] Have you successfully run the Feel++ testsuite with your changes locally?
- [ ] Have you written Doxygen comments in your contribution ?

-----

Fix issue #1605 
correct test cases and add tests for hdg_poisson

### CODE REVIEW

**Comment by prudhomm** [comment]
@romainhild what are the tools available? Postprocessing?  Statistics?

**Comment by prudhomm** [comment]
All the test s run in sequential and in parallel,2d and 3d?
Do you have a Copy/paste of the ctest command?
I often do that in PR

**Comment by romainhild** [comment]
I didn't change that yet, I think I'll do another branch and rewrite the toolbox from what has been done in the other toolboxes.
I think it will be better than changing one thing by one thing.
I would need to change the assembly process, the post process, and the way bdf is handled.

**Comment by prudhomm** [comment]
Do you test space/time solution?
For the parabolic case

**Comment by romainhild** [comment]
Here are the results of the testsuite for hdg_poisson: 
```
16:13:04 hild@atlas6 hdg ctest -R hdg_poisson
Test project /ssd/hild/builds/eye2brain/toolboxes/hdg
    Start 1: feelpp_toolbox_hdg_poisson-quarter-turn-2d-np-6
1/8 Test #1: feelpp_toolbox_hdg_poisson-quarter-turn-2d-np-6 .......   Passed    2.89 sec
    Start 2: feelpp_toolbox_hdg_poisson-quarter-turn-2d-np-1
2/8 Test #2: feelpp_toolbox_hdg_poisson-quarter-turn-2d-np-1 .......   Passed    2.73 sec
    Start 3: feelpp_toolbox_hdg_poisson-quarter-turn-2d-int-np-6
3/8 Test #3: feelpp_toolbox_hdg_poisson-quarter-turn-2d-int-np-6 ...   Passed    2.93 sec
    Start 4: feelpp_toolbox_hdg_poisson-quarter-turn-2d-int-np-1
4/8 Test #4: feelpp_toolbox_hdg_poisson-quarter-turn-2d-int-np-1 ...   Passed    2.77 sec
    Start 5: feelpp_toolbox_hdg_poisson-quarter-turn-3d-np-6
5/8 Test #5: feelpp_toolbox_hdg_poisson-quarter-turn-3d-np-6 .......   Passed    5.87 sec
    Start 6: feelpp_toolbox_hdg_poisson-quarter-turn-3d-np-1
6/8 Test #6: feelpp_toolbox_hdg_poisson-quarter-turn-3d-np-1 .......   Passed   10.02 sec
    Start 7: feelpp_toolbox_hdg_poisson-quarter-turn-3d-int-np-6
7/8 Test #7: feelpp_toolbox_hdg_poisson-quarter-turn-3d-int-np-6 ...   Passed    5.64 sec
    Start 8: feelpp_toolbox_hdg_poisson-quarter-turn-3d-int-np-1
8/8 Test #8: feelpp_toolbox_hdg_poisson-quarter-turn-3d-int-np-1 ...   Passed   10.58 sec

100% tests passed, 0 tests failed out of 8

Total Test time (real) =  43.48 sec
```
I'm compiling the rest of the testsuite to check that.
By the way, there is no more tests when we open a pull request ?

**Comment by romainhild** [comment]
@prudhomm here are the results of the testsuite 
```
98% tests passed, 10 tests failed out of 412

Label Time Summary:
testalg              =  60.95 sec*proc (26 tests)
testcore             = 100.64 sec*proc (50 tests)
testcrb              = 165.66 sec*proc (19 tests)
testdiscr            = 1249.61 sec*proc (114 tests)
testevents           =   4.17 sec*proc (2 tests)
testfilters          =  72.25 sec*proc (20 tests)
testfit              =  10.89 sec*proc (4 tests)
testintegration      =  52.86 sec*proc (16 tests)
testinterpolation    = 403.34 sec*proc (23 tests)
testleaks            =  38.66 sec*proc (16 tests)
testls               =   6.96 sec*proc (3 tests)
testmaterial         =   3.48 sec*proc (2 tests)
testmath             =   3.52 sec*proc (2 tests)
testmesh             =  77.11 sec*proc (28 tests)
testmodels           =  11.61 sec*proc (2 tests)
testopt              =   4.22 sec*proc (2 tests)
testpde              =  24.15 sec*proc (4 tests)
testpoly             =  77.11 sec*proc (20 tests)
testpython           =  13.62 sec*proc (6 tests)
testts               =  17.75 sec*proc (7 tests)
testvf               = 321.82 sec*proc (44 tests)

Total Test time (real) = 2735.31 sec

The following tests did not run:
        333 - feelpp_test_bdf3-np-1 (Skipped)

The following tests FAILED:
        173 - feelpp_test_interpolation_RT-np-1 (Child aborted)
        174 - feelpp_test_interpolation_Nedelec-np-1 (Child aborted)
        175 - feelpp_test_interpolation_Nedelec3d-np-1 (Timeout)
        213 - feelpp_test_hdiv-np-1 (Child aborted)
        214 - feelpp_test_hdiv_oneelt-np-1 (Failed)
        215 - feelpp_test_hdiv3D_oneelt-np-1 (Timeout)
        216 - feelpp_test_hcurl_oneelt-np-1 (Failed)
        218 - feelpp_test_hcurl-np-6 (Failed)
        222 - feelpp_test_hcurl3D_oneelt-np-1 (Timeout)
        236 - feelpp_test_meshstructured-np-6 (Failed)
Errors while running CTest
```

**Comment by romainhild** [comment]
@prudhomm is that possible to merge the branch ?

**Pull request merged**
