### PR TITLE
fix #1229

### LINKED ISSUE #1229: Test feelpp_test_eigenmodes FTE
feelpp_test_eigenmodes currently fails at execution in the check. It should be fairly easy to fix. 

@romainhild could you take care of this. simply use docker feelpp/feelpp:latest and recompile this testsuite exampl

### PR DESCRIPTION
**Pull request by romainhild**
- add options for the position of spectrum: target_magnitude target_real and
target_imaginary
- take them into account in solvereigenslepc
- use it in test eigenmode

- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/feelpp/feelpp/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes?
- [ ] Have you successfully run the Feel++ testsuite with your changes locally?
- [ ] Have you written Doxygen comments in your contribution ?

-----

### CODE REVIEW

**Comment by prudhomm** [comment]
we have a nice macro that checks PETSc or SLEPc version (equal, less or greater) that can be used to check the version

**Comment by romainhild** [comment]
ah yes I didn't think of that, I will add it.

**Comment by romainhild** [comment]
the nice macro is that:
```
#if (SLEPC_VERSION_MAJOR == 3) && (SLEPC_VERSION_MINOR >= 5)
```
?

**Comment by prudhomm** [comment]
maybe ask @vincentchabannes  for guidance about this

**Comment by prudhomm** [comment]
> the nice macro is that:
#if (SLEPC_VERSION_MAJOR == 3) && (SLEPC_VERSION_MINOR >= 5)
?

well nope but I forgot to define it for SLEPc, it is defined only for PETSc (see feelcore/feelpetsc.hpp) 
so do has you wrote above

**Comment by romainhild** [comment]
```
Test project /ssd/hild/builds/develop_debug/testsuite/feelalg
    Start 21: feelpp_test_eigenmode-np-6
1/2 Test #21: feelpp_test_eigenmode-np-6 .......   Passed   11.97 sec
    Start 22: feelpp_test_eigenmode-np-1
2/2 Test #22: feelpp_test_eigenmode-np-1 .......   Passed   12.71 sec

100% tests passed, 0 tests failed out of 2

Label Time Summary:
testalg    =  24.69 sec*proc (2 tests)

Total Test time (real) =  24.69 sec
```

**Pull request merged**
