### PR TITLE
Feature/remesh

### PR DESCRIPTION
**Pull request by prudhomm**
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/feelpp/feelpp/pulls) for the same change?
- [X] Have you added an explanation of what your changes do and why you'd like us to include them?
- [X] Have you written new tests for your changes?
- [X] Have you successfully run the Feel++ testsuite with your changes locally?
- [ ] Have you written Doxygen comments in your contribution ?

-----
implements #1430 #1445 #1448 and has some hints for #1431

### CODE REVIEW

**Comment by vincentchabannes** [comment]
@prudhomm there is a problem with the submodule parmmg, see [here](https://buildkite.com/feelpp/feelpp/builds/3397#96f3cf92-eec3-4147-9bc7-03a81e6c3bbc/13-241)

**Comment by prudhomm** [comment]
ok I will look at that. how about the rest ?

**Comment by vincentchabannes** [comment]
When buildkite will be green, we can merge

**Comment by prudhomm** [comment]
I forgot to push the feelpp branch. this is fixed and buildkite is running now

**Comment by prudhomm** [comment]
here are the results of the testsuite:
```
The following tests FAILED:
	 37 - feelpp_test_worldcomm-np-6 (Timeout)
	113 - feelpp_test_remesh-np-6 (Failed)
	114 - feelpp_test_remesh-np-1 (Failed)
	218 - feelpp_test_hcurl-np-6 (Failed)
	236 - feelpp_test_meshstructured-np-6 (Failed)
	306 - feelpp_test_eim-np-1 (Timeout)
	307 - feelpp_test_eim_grepl-np-6 (Failed)
	308 - feelpp_test_eim_grepl-np-1 (Timeout)
	309 - feelpp_test_eim_composite-np-1 (Timeout)
Errors while running CTest
```
I am investigating the remesh issues

**Comment by prudhomm** [comment]
test_remesh ok
```
Test project /home/prudhomm/scratch/feelpp.clang8.release/testsuite/feelmesh
    Start 29: feelpp_test_remesh-np-1
1/1 Test #29: feelpp_test_remesh-np-1 ..........   Passed    2.37 sec

100% tests passed, 0 tests failed out of 1

Label Time Summary:
testmesh    =   2.37 sec*proc (1 test)

Total Test time (real) =   2.39 sec
```

**Comment by prudhomm** [comment]
`test_eim` are good after `rm -rf $HOME/crbdb`
```
ctest -R test_eim                                    [10:34:13]
Test project /home/prudhomm/scratch/feelpp.clang8.release/testsuite
    Start 305: feelpp_test_eim-np-1
1/4 Test #305: feelpp_test_eim-np-1 .............   Passed    5.79 sec
    Start 306: feelpp_test_eim_grepl-np-6
2/4 Test #306: feelpp_test_eim_grepl-np-6 .......   Passed    4.10 sec
    Start 307: feelpp_test_eim_grepl-np-1
3/4 Test #307: feelpp_test_eim_grepl-np-1 .......   Passed    4.31 sec
    Start 308: feelpp_test_eim_composite-np-1
4/4 Test #308: feelpp_test_eim_composite-np-1 ...   Passed   11.09 sec

100% tests passed, 0 tests failed out of 4

Label Time Summary:
testcrb    =  25.29 sec*proc (4 tests)

Total Test time (real) =  25.37 sec
```

**Pull request merged**
