### PR TITLE
Holo3 Image Correlation

### PR DESCRIPTION
**Pull request by LANTZT**
This will update and introduce into Feelpp all the files develop during the internship linked to this subject.
It will also allow to update the version install on a server at Holo3, in order to be used later.

The resolution of the image correlation problem doesn't work right now and it's still "work in progress" .
#571 #572 #573 #586 #587

### CODE REVIEW

**Comment by prudhomm** [comment]
how is it working now ?

**Comment by LANTZT** [comment]
I manage to find the error which gave me difference values than the Octave/Matlab code.
Now I have the same result at each step, I test it on different easy functions ( x, sin(x), y*y, ...) 
But the visualization on Paraview didn't really change and it's still bad.

**Comment by prudhomm** [comment]
Ok great ! what was it ? at which step ?
you see sometimes there are no ways to avoid this kind of hard search for the bugs

**Comment by prudhomm** [comment]
now there might be another issue somewhere, you tested only the fft on each element no ?
or are you trying on the complete system ?
first thing is try simple functions, say `x` (gradient is easy)  and check using the `print` returns the proper values for the gradient

**Comment by LANTZT** [comment]
Yep 
It was the construction of the waves number vector, the fftshift method I develop and use it didn't work well and return me something different than what I want and what is used in Octave.

**Comment by LANTZT** [comment]
At this time, I used the FFT method on each element and I store all results in an array. Then I retrieve the value with real coordinates and reference one ( to define element for nodes at the boundary ).
The print didn't give me the good value in theory ( with  x for example ) but on Praview, it also different than what I can see .

**Pull request merged**
