### PR TITLE
Feature/ls refactoring

### PR DESCRIPTION
**Pull request by vincentchabannes**
This branch provides eulerian interface tracking using the level-set method. It allows to simulate flowing objects with or without surrounding membranes and couples the fluid and the flowing structures using an explicit modular scheme.
It thus provides an Advection-Diffusion-Reaction toolbox, with several stabilisation strategies, the LevelSet toolbox, which solves for the level-set transport equation, multiple redistanciation solvers to keep the level-set close to a distance function and the MultiFluid toolbox, which handles the coupling between the level-set and the fluid. The MultiFluid toolbox can also take into account membrane forces including the proper simulation of thin shell mechanics.

- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/feelpp/feelpp/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes?
- [x] Have you successfully run the Feel++ testsuite with your changes locally?

-----

### CODE REVIEW

**Comment by vincentchabannes** [comment]
@metivett Could you fill the  pull request description?

**Comment by metivett** [comment]
@vincentchabannes Sure ! Shall I write it here in the comments ?

**Comment by vincentchabannes** [comment]
yes here (at the top if you can)

**Comment by metivett** [comment]
This branch provides eulerian interface tracking using the level-set method. It allows to simulate flowing objects with or without surrounding membranes and couples the fluid and the flowing structures using an explicit modular scheme.
It thus provides an `Advection-Diffusion-Reaction` toolbox, with several stabilisation strategies,  the `LevelSet` toolbox, which solves for the level-set transport equation, multiple redistanciation solvers to keep the level-set close to a distance function and the `MultiFluid` toolbox, which handles the coupling between the level-set and the fluid. The `MultiFluid` toolbox can also take into account membrane forces including the proper simulation of thin shell mechanics.

**Pull request merged**
