### PR TITLE
new file organisation for Feel++

### PR DESCRIPTION
**Pull request by prudhomm**
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/feelpp/feelpp/pulls) for the same change?
- [X] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes?
- [ ] Have you successfully run the Feel++ testsuite with your changes locally?
- [ ] Have you written Doxygen comments in your contribution ?

-----

This implements:
 - #1208  
 - #1212 
 - #930

### CODE REVIEW

**Comment by prudhomm** [comment]
The testsuite needs now to be run

**Comment by prudhomm** [comment]
@vincentchabannes here is the status of the testsuite in the branch:

```
97% tests passed, 5 tests failed out of 193

Label Time Summary:
testalg              =   9.62 sec*proc (12 tests)
testcore             =   9.27 sec*proc (19 tests)
testcrb              =  73.72 sec*proc (9 tests)
testdiscr            = 268.87 sec*proc (62 tests)
testfilters          =  27.48 sec*proc (7 tests)
testfit              =   1.36 sec*proc (2 tests)
testintegration      =  10.60 sec*proc (7 tests)
testinterpolation    =  48.79 sec*proc (16 tests)
testleaks            =   7.16 sec*proc (8 tests)
testls               =   1.40 sec*proc (2 tests)
testmaterial         =   0.26 sec*proc (1 test)
testmath             =   0.27 sec*proc (1 test)
testmesh             =  19.88 sec*proc (12 tests)
testmodels           =   1.81 sec*proc (1 test)
testpde              =   5.73 sec*proc (2 tests)
testpoly             =  13.80 sec*proc (9 tests)
testts               =   3.10 sec*proc (5 tests)
testvf               =  38.79 sec*proc (18 tests)

Total Test time (real) = 186.99 sec

The following tests did not run:
	 96 - feelpp_test_space_0d-np-1 (Skipped)
	159 - feelpp_test_bdf3-np-1 (Skipped)
	165 - feelpp_test_laplacianv-np-1 (Skipped)
	166 - feelpp_test_laplacian-np-1 (Skipped)
	167 - feelpp_test_laplaciant-np-1 (Skipped)

The following tests FAILED:
	 18 - feelpp_test_serialization-np-1 (Failed)
	154 - feelpp_test_db-np-1 (Failed)
	160 - feelpp_test_bdf_reverse-np-1 (Not Run)
	161 - feelpp_test_bdf_forward-np-1 (Not Run)
	168 - feelpp_test_inner_curl-np-1 (Not Run)
Errors while running CTest
```

what is currently expected to fail ?

**Comment by vincentchabannes** [comment]
In release mode, only feelpp_test_inner_curl because it doesn't compile (there is curlx in 2d, for me, it's normal  to have an error compilation, but maybe it's useful somewhere)

**Comment by prudhomm** [comment]
the bdf issue is just an include issue. it is being fixed. how db and serialization are always nasty ones, they work not very reliably

**Comment by prudhomm** [comment]
bdf fixed:
```
The following tests FAILED:
	 18 - feelpp_test_serialization-np-1 (Failed)
	154 - feelpp_test_db-np-1 (Failed)
	168 - feelpp_test_inner_curl-np-1 (Not Run)
Errors while running CTest
```

**Comment by prudhomm** [comment]
in test_db I get this

```
 Checking basis sizes ...
7: WN0:size=6 ; WN1:size=5
7: /home/prudhomm/Devel/feelpp.dyn/testsuite/feelcrb/test_db.cpp(306): error: in "crb_db/crd_db_test1": check wnSize[0] == wnSize[i] has failed
7: WN0:size=6 ; WN2:size=6
7: WN0:size=6 ; WN3:size=5
7: /home/prudhomm/Devel/feelpp.dyn/testsuite/feelcrb/test_db.cpp(306): error: in "crb_db/crd_db_test1": check wnSize[0] == wnSize[i] has failed
7: Basis sizes OK
7: Checking Number of samples ...
```
it seems like a tolerance issue

**Pull request merged**
