### PR TITLE
resolves 2123:  enable dim different from realdim in BVH

### LINKED ISSUE #2123: Enable dim != realdim for BVH
Enable the construction of Bounding Volume Hierarchies from surface-only mesh data

- [x] #2152

### PR DESCRIPTION
**Pull request by prudhomm**
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/feelpp/feelpp/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes?
- [ ] Have you successfully run the Feel++ testsuite with your changes locally?
- [ ] Have you written Doxygen comments in your contribution ?

-----
Enable BVH to be constructed for surface-only meshes in 3d
- closes #2123

### CODE REVIEW

**Comment by prudhomm** [comment]
@lberti @vincentchabannes I had to rename the branch because `=` is not supported in tags by docker and it was breaking our build system

**Comment by vincentchabannes** [comment]
@prudhomm my review has disappeared??

**Comment by prudhomm** [comment]
No it is in the other PR.
I had to rename the branch to get it compiled

**Comment by prudhomm** [comment]
Your review is here https://github.com/feelpp/feelpp/pull/2124. @vincentchabannes

**Comment by prudhomm** [comment]
@lberti the testsuite compilation is currenttly broken  : https://buildkite.com/feelpp/feelpp/builds/4961#01891618-9db1-4ff6-8332-86db92cb3863/104-439

**Comment by lberti** [comment]
@vincentchabannes I have addressed all you comments from https://github.com/feelpp/feelpp/pull/2124, but handling the memory leaks due to the pointer is still pending

**Review by vincentchabannes — APPROVED** [review]

**Pull request merged**
