### PR TITLE
Refactor/mor

### PR DESCRIPTION
**Pull request by prudhomm**
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/feelpp/feelpp/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes?
- [x] Have you successfully run the Feel++ testsuite with your changes locally?
- [ ] Have you written Doxygen comments in your contribution ?

-----

THis PR implements (#1740) the refactoring of the MOR framework, everything MOR related is in mor now. It allows specific developments and reduced dev and compilation cycles

### CODE REVIEW

**Comment by prudhomm** [comment]
this is still a work in progress, in particular the TODO list:

- [ ] move tests from testsuite to mor
- [ ] merge work by @romainhild into the branch
- [ ] add new tests

**Comment by prudhomm** [comment]
@vincentchabannes you can already review what has already been done. There are still a few things to do (see above)

**Review by vincentchabannes — COMMENTED** [review]
seems ok for me. My note : the cmake functions crb_add_model or crb_add_lib.. should be kept, there are really link to reduced basis framework, not in a generic model order reduction

**Comment by prudhomm** [comment]
@thomas-saigre did you manage to merge your work with refactor/mor

**Comment by prudhomm** [comment]
all done with branch. buildkite is green, last test with merging develop on the way
/cc @vincentchabannes @romainhild

**Comment by prudhomm** [comment]
https://buildkite.com/feelpp/feelpp/builds?branch=refactor%2Fmor

**Pull request merged**
