### PR TITLE
reduce memory footprint #1317

### PR DESCRIPTION
**Pull request by prudhomm**
- implement invalid_v<> to get the invalid value for an unsigned type
  this allows to make the transition to template type for indices
- set index_type/size_type to be uint32_type in mesh data structures
- not yet done in comm and FunctionSpace/dof/forms (only the mesh related stuff
  is mostly done)
- a few classes become template classes like MeshBase with template type IndexT
  to parametrize the indices type

- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/feelpp/feelpp/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes?
- [x] Have you successfully run the Feel++ testsuite with your changes locally?
- [ ] Have you written Doxygen comments in your contribution ?

-----

### CODE REVIEW

**Comment by prudhomm** [comment]
here is the status of the testsuite:
```
The following tests FAILED:                                                                                                                                            
         83 - feelpp_test_entity-np-6 (Failed)                                                                                                                         
         84 - feelpp_test_entity-np-1 (Failed)                                                                                                                         
        130 - feelpp_test_importergmsh-np-1 (SEGFAULT)                                                                                                                 
        156 - feelpp_test_operatorinterpolation-np-6 (Failed)                                                                                                          
        157 - feelpp_test_operatorinterpolation-np-1 (Failed)                                                                                                          
        167 - feelpp_test_darcy_on_2d-np-6 (Failed)                                                                                                                    
        168 - feelpp_test_darcy_on_2d-np-1 (Failed)                                                                                                                    
        169 - feelpp_test_darcy_on_3d-np-6 (Failed)                                                                                                                    
        170 - feelpp_test_darcy_on_3d-np-1 (Failed)                                                                                                                    
        183 - feelpp_test_integration_relatedmesh-np-6 (Timeout)                                                                                                       
        184 - feelpp_test_integration_relatedmesh-np-1 (Failed)                                                                                                        
        263 - feelpp_test_mortar-np-1 (Child aborted)                                                                                                                  
        264 - feelpp_test_mortar2-np-1 (Failed)                                                                                                                        
        266 - feelpp_test_extended-np-6 (Failed)                                                                                                                       
        267 - feelpp_test_extended-np-1 (Child aborted)                                                                                                                
        296 - feelpp_test_eim-np-1 (Failed)                                                                                                                            
        297 - feelpp_test_eim_grepl-np-6 (Failed)                                                                                                                      
        298 - feelpp_test_eim_grepl-np-1 (Failed)                                                                                                                      
        299 - feelpp_test_eim_composite-np-1 (Failed)                                                                                                                  
        348 - feelpp_test_forms-np-6 (Failed)                                                                                                                          
        349 - feelpp_test_forms-np-1 (Failed)                                                                                                                          
Errors while running CTest 
```

**Comment by prudhomm** [comment]
update of the testsuite status:
```
The following tests FAILED:                                                                                                                                            
         83 - feelpp_test_entity-np-6 (Failed)                                                                                                                         
         84 - feelpp_test_entity-np-1 (Failed)                                                                                                                         
        130 - feelpp_test_importergmsh-np-1 (SEGFAULT)                                                                                                                 
        156 - feelpp_test_operatorinterpolation-np-6 (Failed)                                                                                                          
        157 - feelpp_test_operatorinterpolation-np-1 (Failed)                                                                                                          
        167 - feelpp_test_darcy_on_2d-np-6 (Failed)                                                                                                                    
        168 - feelpp_test_darcy_on_2d-np-1 (Failed)                                                                                                                    
        169 - feelpp_test_darcy_on_3d-np-6 (Failed)                                                                                                                    
        170 - feelpp_test_darcy_on_3d-np-1 (Failed)                                                                                                                    
        296 - feelpp_test_eim-np-1 (Failed)                                                                                                                            
        297 - feelpp_test_eim_grepl-np-6 (Failed)                                                                                                                      
        298 - feelpp_test_eim_grepl-np-1 (Failed)                                                                                                                      
        299 - feelpp_test_eim_composite-np-1 (Failed)                                                                                                                  
Errors while running CTest                                                                                                                                             
```

**Comment by prudhomm** [comment]
new status, the failures are not related to the PR
```
The following tests FAILED:                                                                                                                                            
        130 - feelpp_test_importergmsh-np-1 (SEGFAULT)                                                                                                                 
        156 - feelpp_test_operatorinterpolation-np-6 (Failed)                                                                                                          
        157 - feelpp_test_operatorinterpolation-np-1 (Failed)                                                                                                          
        167 - feelpp_test_darcy_on_2d-np-6 (Failed)                                                                                                                    
        169 - feelpp_test_darcy_on_3d-np-6 (Failed)                                                                                                                    
        170 - feelpp_test_darcy_on_3d-np-1 (Failed)                                                                                                                    
        296 - feelpp_test_eim-np-1 (Failed)                                                                                                                            
        297 - feelpp_test_eim_grepl-np-6 (Failed)                                                                                                                      
        298 - feelpp_test_eim_grepl-np-1 (Failed)                                                                                                                      
        299 - feelpp_test_eim_composite-np-1 (Failed)                                                                                                                  
Errors while running CTest 
```

**Comment by prudhomm** [comment]
here are the results of the toolboxes testsuite @vincentchabannes 
```
ctest -R .
Test project /home/prudhomm/scratch/feelpp/hdg.clang.release/toolboxes
      Start  1: feelpp_toolbox_fluid-TurekHron-cfd1-np-6
 1/10 Test  #1: feelpp_toolbox_fluid-TurekHron-cfd1-np-6 ...   Passed    4.88 sec
      Start  2: feelpp_toolbox_fluid-TurekHron-cfd1-np-1
 2/10 Test  #2: feelpp_toolbox_fluid-TurekHron-cfd1-np-1 ...   Passed    7.30 sec
      Start  3: feelpp_toolbox_fluid-TurekHron-cfd2-np-6
 3/10 Test  #3: feelpp_toolbox_fluid-TurekHron-cfd2-np-6 ...   Passed    6.25 sec
      Start  4: feelpp_toolbox_fluid-TurekHron-cfd2-np-1
 4/10 Test  #4: feelpp_toolbox_fluid-TurekHron-cfd2-np-1 ...   Passed    9.08 sec
      Start  5: feelpp_toolbox_fluid-TurekHron-cfd3-np-6
 5/10 Test  #5: feelpp_toolbox_fluid-TurekHron-cfd3-np-6 ...   Passed   14.22 sec
      Start  6: feelpp_toolbox_fluid-TurekHron-cfd3-np-1
 6/10 Test  #6: feelpp_toolbox_fluid-TurekHron-cfd3-np-1 ...   Passed   24.48 sec
      Start  7: feelpp_toolbox_solid-TurekHron-csm1-np-6
 7/10 Test  #7: feelpp_toolbox_solid-TurekHron-csm1-np-6 ...   Passed   10.39 sec
      Start  8: feelpp_toolbox_solid-TurekHron-csm1-np-1
 8/10 Test  #8: feelpp_toolbox_solid-TurekHron-csm1-np-1 ...   Passed    6.62 sec
      Start  9: feelpp_toolbox_solid-TurekHron-csm2-np-6
 9/10 Test  #9: feelpp_toolbox_solid-TurekHron-csm2-np-6 ...   Passed    8.60 sec
      Start 10: feelpp_toolbox_solid-TurekHron-csm2-np-1
10/10 Test #10: feelpp_toolbox_solid-TurekHron-csm2-np-1 ...   Passed    5.58 sec

100% tests passed, 0 tests failed out of 10

Total Test time (real) =  97.50 sec
```

**Comment by prudhomm** [comment]
here is the status of the testsuite:

```
99% tests passed, 5 tests failed out of 388

Label Time Summary:
testalg              =  19.73 sec*proc (24 tests)
testcore             =  27.19 sec*proc (50 tests)
testcrb              =  83.25 sec*proc (15 tests)
testdiscr            = 330.89 sec*proc (111 tests)
testevents           =   1.43 sec*proc (2 tests)
testfilters          =  44.07 sec*proc (15 tests)
testfit              =   3.12 sec*proc (4 tests)
testintegration      =  17.55 sec*proc (14 tests)
testinterpolation    =  54.71 sec*proc (23 tests)
testleaks            =  13.98 sec*proc (16 tests)
testls               =   2.42 sec*proc (3 tests)
testmaterial         =   0.51 sec*proc (2 tests)
testmath             =   0.54 sec*proc (2 tests)
testmesh             =  38.21 sec*proc (26 tests)
testmodels           =   2.62 sec*proc (2 tests)
testopt              =   1.49 sec*proc (2 tests)
testpde              =   8.98 sec*proc (4 tests)
testpoly             =  31.75 sec*proc (20 tests)
testpython           =   6.67 sec*proc (6 tests)
testts               =   8.37 sec*proc (7 tests)
testvf               =  71.80 sec*proc (40 tests)

Total Test time (real) = 775.68 sec

The following tests did not run:
	315 - feelpp_test_bdf3-np-1 (Skipped)
	326 - feelpp_test_laplacianv-np-6 (Skipped)
	327 - feelpp_test_laplacianv-np-1 (Skipped)
	328 - feelpp_test_laplacian-np-6 (Skipped)
	329 - feelpp_test_laplacian-np-1 (Skipped)
	330 - feelpp_test_laplaciant-np-6 (Skipped)
	331 - feelpp_test_laplaciant-np-1 (Skipped)

The following tests FAILED:
	130 - feelpp_test_importergmsh-np-1 (SEGFAULT)
	156 - feelpp_test_operatorinterpolation-np-6 (Failed)
	157 - feelpp_test_operatorinterpolation-np-1 (Failed)
	167 - feelpp_test_darcy_on_2d-np-6 (Failed)
	169 - feelpp_test_darcy_on_3d-np-6 (Failed)
Errors while running CTest
```

**Comment by prudhomm** [comment]
@vincentchabannes there is still the issue with OperatorInterpolation for RT elements

**Comment by prudhomm** [comment]
@vincentchabannes I think this  branch can be safely merged into `feature/sc-geomap`. ok for you ?

**Comment by vincentchabannes** [comment]
@prudhomm the test OperatorInterpolation is ok in sc-geomap (tested on atlas and with buildkite, see [here](https://buildkite.com/feelpp/feelpp-testsuite/builds/196#d7422c1e-5f92-47f1-a5b5-186d4f05fc50).
Something is maybe wrong in this branch

**Comment by prudhomm** [comment]
All expected tests are now passing at cemosis.feelpp.org, let's see what docker says and we may be good to go with the big merge !

**Pull request merged**
