### PR TITLE
Hdg testcases

### PR DESCRIPTION
**Pull request by thomas-saigre**
Add `directory` argument in cfg files for hdg poisson test cases, to savec results in a same directory

Fix test cases in hdg/poisson

Add templated function to make convergence test with toolboxes.

- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/feelpp/feelpp/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? 
- [ ] Have you successfully run the Feel++ testsuite with your changes locally?
- [ ] Have you written Doxygen comments in your contribution ?

-----

### CODE REVIEW

**Review by prudhomm — APPROVED** [review]

**Comment by prudhomm** [comment]
@romainhild @thomas-saigre have you added the various hdg testcase to ctest ?

**Comment by prudhomm** [comment]
could you do it and run ctest on this branch with respect to hdg ?

**Comment by romainhild** [comment]
@prudhomm can we merge this branch and I will add the tests in the branch thomas-saigre/issue1605 ?

**Comment by prudhomm** [comment]
Everything is running properly?
Tool boxes. Testsuite
Testsuite
Quick start testsuite?

**Comment by romainhild** [comment]
I'm not sure, I haven't run everything.
We can close this issue and I'll merge it into the other branch. I'll run the tests there it will be simplier.

**Pull request closed without merging**
