### PR TITLE
Issue #672: Exporter prefix

### PR DESCRIPTION
**Pull request by aancel**
Proposition for issue #672 :
- [ ] Allow to change the name of a timeset instance (feel/feeldisc)
- [ ] Set the name of a timeset from the exporter with the setPrefix function (previously it was notably set when an instance of an exporter is created)
  - [ ] Maybe only allow to use the setName function from timeset to selected classes (`friend` ?)
  - [ ] Have a setPrefix( name ) function fo the last timeset, allow modification for other timsets with setPrefix( id, name )
- [ ] Update the exporters to only use the name of the timesets and not the prefix set in the bae exporter class

### CODE REVIEW

**Comment by aancel** [comment]
@gdolle test_bdf3 is now working with this branch (both test1 and 2)

**Comment by prudhomm** [comment]
@aancel could you post an example of the resulting case file generated if one timeset and multiple timeset ?

**Comment by aancel** [comment]
@prudhomm It won't fundamentally change how the case file will be generated.
For example, when using @gdolle's test: test_bdf3, 2 case files will be output, one per timeset, whereas before the export was failing for the second timeset if I remember well, so you would have:
rhs_0.case
```
FORMAT:
type: ensight gold
GEOMETRY:
model: rhs_0.geo
VARIABLES:
scalar per node: 1 u0 rhs_0.u0.scl.****
TIME:
time set:        1
number of steps: 20
filename start number: 1
filename increment: 1
time values: 0.000000e+00 5.000000e-02 1.000000e-01 1.500000e-01 2.000000e-01 2.500000e-01 3.000000e-01 3.500000e-01 4.000000e-01 4.500000e-01
5.000000e-01 5.500000e-01 6.000000e-01 6.500000e-01 7.000000e-01 7.500000e-01 8.000000e-01 8.500000e-01 9.000000e-01 9.500000e-01
```
and 
```
FORMAT:
type: ensight gold
GEOMETRY:
model: rhs_1.geo
VARIABLES:
scalar per node: 1 u1 rhs_1.u1.scl.****
TIME:
time set:        1
number of steps: 20
filename start number: 1
filename increment: 1
time values: 0.000000e+00 5.000000e-02 1.000000e-01 1.500000e-01 2.000000e-01 2.500000e-01 3.000000e-01 3.500000e-01 4.000000e-01 4.500000e-01
5.000000e-01 5.500000e-01 6.000000e-01 6.500000e-01 7.000000e-01 7.500000e-01 8.000000e-01 8.500000e-01 9.000000e-01 9.500000e-01
```

It is more a matter of bugfixing rather than modifying how .case files are output.

**Comment by aancel** [comment]
@gdolle Did you test the branch ?
@prudhomm What do you think of the changes ? Shall I continue to modify the exporters or do we drop the idea ?

**Comment by prudhomm** [comment]
@aancel could you remerge with develop and let travis check that everything is ok with this PR ?

**Pull request merged**
