### PR TITLE
replace boost::filesystem by std::filesystem

### PR DESCRIPTION
**Pull request by metivett**
Replaces boost::filesystem with std::filesystem to reduce boost dependency.

- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/feelpp/feelpp/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes?
- [x] Have you successfully run the Feel++ testsuite with your changes locally?

-----

### CODE REVIEW

**Comment by prudhomm** [comment]
merged with develop
I will review this weekend

**Comment by prudhomm** [comment]
@metivett this fails https://buildkite.com/feelpp/feelpp/builds/4323#283f4c92-8da0-4c22-9f1f-24a64793afbc/6-11239
I will check the dependencies asap
there is no one-to-one correspondence between boost::filesystem and std::filesystem so it may not be just switching boost:: to std::

**Comment by metivett** [comment]
> @metivett this fails https://buildkite.com/feelpp/feelpp/builds/4323#283f4c92-8da0-4c22-9f1f-24a64793afbc/6-11239 I will check the dependencies asap there is no one-to-one correspondence between boost::filesystem and std::filesystem so it may not be just switching boost:: to std::

Indeed, that's why I had to change a few things in https://github.com/feelpp/feelpp/pull/1801/commits/caeed9df04439b1c55df463a9d957d49d53f8839.
However, I don't understand why we have the `error: no namespace named 'filesystem' in namespace 'std'` in buildkite, there should be such a namespace...

**Comment by prudhomm** [comment]
@metivett it is probably a problem with the GCC version. We use clang but clang uses libstdc++ and I think that std::filesystem is available only in GCC9. 
I have to check the dependency version on GCC

**Comment by prudhomm** [comment]
@metivett I just checked and we use GCC 9. Also `std::filesystem` is properly defined for c++17 in GCC9
see eg ` /usr/include/c++/9/bits/fs_fwd.h`
I will have a closer look, perhaps later today

**Comment by prudhomm** [comment]
@metivett in the mean time you can start docker 
```
docker run --rm -it ghcr.io/feelpp/feelpp-env:ubuntu-20.04
```
get your branch and compile to see what is going on

**Comment by vincentchabannes** [comment]
@prudhomm this PR is ready.

**Review by prudhomm — APPROVED** [review]

**Pull request merged**
