### PR TITLE
Feature/python

### PR DESCRIPTION
**Pull request by prudhomm**
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/feelpp/feelpp/pulls) for the same change?
- [X] Have you added an explanation of what your changes do and why you'd like us to include them?
- [X] Have you written new tests for your changes?
- [ ] Have you successfully run the Feel++ testsuite with your changes locally?
- [ ] Have you written Doxygen comments in your contribution ?

-----
support python wrapping see #930 (Epic) and associated issues.

Two more important (breaking) changes in Feel++ though to ease the python bindings process: 
 - use std::shared_ptr instead of boost::shared_ptr see #1202 
 - have consistent storage of `WorldComm` as `std::shared_ptr` rather than `WorldComm` itself or `WorldComm const&` see #1205

### CODE REVIEW

**Comment by prudhomm** [comment]
Results of the testsuite
```
95% tests passed, 20 tests failed out of 372

Label Time Summary:
testalg              =  15.69 sec*proc (22 tests)
testcore             =  22.64 sec*proc (44 tests)
testcrb              =  90.32 sec*proc (15 tests)
testdiscr            = 344.51 sec*proc (111 tests)
testfilters          =  44.83 sec*proc (15 tests)
testfit              =   2.56 sec*proc (4 tests)
testintegration      =  17.06 sec*proc (14 tests)
testinterpolation    =  51.51 sec*proc (25 tests)
testleaks            =  12.38 sec*proc (16 tests)
testls               =   2.01 sec*proc (3 tests)
testmaterial         =   0.73 sec*proc (2 tests)
testmath             =   0.78 sec*proc (2 tests)
testmesh             =  35.33 sec*proc (26 tests)
testmodels           =   2.13 sec*proc (2 tests)
testopt              =   2.41 sec*proc (4 tests)
testpde              =   9.15 sec*proc (4 tests)
testpoly             =  27.42 sec*proc (18 tests)
testts               =   7.40 sec*proc (7 tests)
testvf               =  51.38 sec*proc (38 tests)

Total Test time (real) = 743.20 sec

The following tests did not run:
	188 - feelpp_test_space_0d-np-6 (Skipped)
	189 - feelpp_test_space_0d-np-1 (Skipped)
	301 - feelpp_test_bdf3-np-1 (Skipped)
	310 - feelpp_test_laplacianv-np-6 (Skipped)
	311 - feelpp_test_laplacianv-np-1 (Skipped)
	312 - feelpp_test_laplacian-np-6 (Skipped)
	313 - feelpp_test_laplacian-np-1 (Skipped)
	314 - feelpp_test_laplaciant-np-6 (Skipped)
	315 - feelpp_test_laplaciant-np-1 (Skipped)
	326 - feelpp_test_convolve-np-6 (Skipped)

The following tests FAILED:
	 41 - feelpp_test_serialization-np-6 (Failed)
	 42 - feelpp_test_serialization-np-1 (Failed)
	111 - feelpp_test_immultiscale-np-6 (Failed)
	112 - feelpp_test_immultiscale-np-1 (Failed)
	125 - feelpp_test_med-np-1 (Failed)
	165 - feelpp_test_integration_ifaces-np-6 (Failed)
	228 - feelpp_test_projector-np-6 (Failed)
	272 - feelpp_test_productspaces-np-6 (Failed)
	282 - feelpp_test_eim-np-1 (Not Run)
	283 - feelpp_test_eim_grepl-np-1 (Not Run)
	284 - feelpp_test_eim_composite-np-1 (Not Run)
	287 - feelpp_test_rbspace-np-6 (Failed)
	288 - feelpp_test_rbspace-np-1 (Not Run)
	289 - feelpp_test_rbspacevector-np-6 (Failed)
	290 - feelpp_test_rbspacevector-np-1 (Not Run)
	291 - feelpp_test_db-np-6 (Failed)
	292 - feelpp_test_db-np-1 (Not Run)
	318 - feelpp_test_inner_curl-np-6 (Failed)
	319 - feelpp_test_inner_curl-np-1 (Not Run)
	354 - feelpp_test_solve_leak-np-6 (Failed)
Errors while running CTest
```

**Comment by prudhomm** [comment]
Current state of the testsuite
```
92% tests passed, 28 tests failed out of 372

Label Time Summary:
testalg              =  17.45 sec*proc (22 tests)
testcore             =  25.30 sec*proc (44 tests)
testcrb              =  19.51 sec*proc (15 tests)
testdiscr            = 398.05 sec*proc (111 tests)
testfilters          =  58.60 sec*proc (15 tests)
testfit              =   3.19 sec*proc (4 tests)
testintegration      =  20.33 sec*proc (14 tests)
testinterpolation    =  60.19 sec*proc (25 tests)
testleaks            =  13.78 sec*proc (16 tests)
testls               =   2.38 sec*proc (3 tests)
testmaterial         =   0.71 sec*proc (2 tests)
testmath             =   0.63 sec*proc (2 tests)
testmesh             =  43.43 sec*proc (26 tests)
testmodels           =   2.08 sec*proc (2 tests)
testopt              =   2.66 sec*proc (4 tests)
testpde              =   9.88 sec*proc (4 tests)
testpoly             =  28.95 sec*proc (18 tests)
testts               =   8.53 sec*proc (7 tests)
testvf               =  58.66 sec*proc (38 tests)

Total Test time (real) = 396.53 sec

The following tests did not run:
	188 - feelpp_test_space_0d-np-6 (Skipped)
	189 - feelpp_test_space_0d-np-1 (Skipped)
	301 - feelpp_test_bdf3-np-1 (Skipped)
	310 - feelpp_test_laplacianv-np-6 (Skipped)
	311 - feelpp_test_laplacianv-np-1 (Skipped)
	312 - feelpp_test_laplacian-np-6 (Skipped)
	313 - feelpp_test_laplacian-np-1 (Skipped)
	314 - feelpp_test_laplaciant-np-6 (Skipped)
	315 - feelpp_test_laplaciant-np-1 (Skipped)
	326 - feelpp_test_convolve-np-6 (Skipped)

The following tests FAILED:
	 41 - feelpp_test_serialization-np-6 (Failed)
	 42 - feelpp_test_serialization-np-1 (Failed)
	 54 - feelpp_test_vector-np-6 (Failed)
	 55 - feelpp_test_vector-np-1 (Failed)
	111 - feelpp_test_immultiscale-np-6 (Failed)
	112 - feelpp_test_immultiscale-np-1 (Failed)
	125 - feelpp_test_med-np-1 (Failed)
	165 - feelpp_test_integration_ifaces-np-6 (Failed)
	167 - feelpp_test_integration_opt-np-6 (Failed)
	206 - feelpp_test_functionals-np-1 (Failed)
	215 - feelpp_test_meshstructured-np-6 (Failed)
	216 - feelpp_test_meshstructured-np-1 (Failed)
	228 - feelpp_test_projector-np-6 (Failed)
	272 - feelpp_test_productspaces-np-6 (Failed)
	280 - feelpp_test_twospacesmap-np-6 (Failed)
	281 - feelpp_test_twospacesmap-np-1 (Failed)
	282 - feelpp_test_eim-np-1 (Failed)
	283 - feelpp_test_eim_grepl-np-1 (Failed)
	284 - feelpp_test_eim_composite-np-1 (Failed)
	285 - feelpp_test_deim-np-6 (Failed)
	286 - feelpp_test_deim-np-1 (Failed)
	291 - feelpp_test_db-np-6 (Failed)
	292 - feelpp_test_db-np-1 (Failed)
	295 - feelpp_test_reducedglobaldof-np-6 (Failed)
	296 - feelpp_test_reducedglobaldof-np-1 (Failed)
	318 - feelpp_test_inner_curl-np-6 (Failed)
	319 - feelpp_test_inner_curl-np-1 (Not Run)
	354 - feelpp_test_solve_leak-np-6 (Failed)
Errors while running CTest
```

**Comment by prudhomm** [comment]
`MeshStructured` tests fixed:

```
ctest -R structured
Test project /home/prudhomm/scratch/feelpp/dyn.clang.release/testsuite
    Start 215: feelpp_test_meshstructured-np-6
1/2 Test #215: feelpp_test_meshstructured-np-6 ...   Passed    0.78 sec
    Start 216: feelpp_test_meshstructured-np-1
2/2 Test #216: feelpp_test_meshstructured-np-1 ...   Passed    0.55 sec

100% tests passed, 0 tests failed out of 2

Label Time Summary:
testdiscr    =   1.34 sec*proc (2 tests)

Total Test time (real) =   1.35 sec
```

**Comment by prudhomm** [comment]
testsuite

```
95% tests passed, 17 tests failed out of 372

Label Time Summary:
testalg              =  18.23 sec*proc (22 tests)
testcore             =  25.51 sec*proc (44 tests)
testcrb              = 112.19 sec*proc (15 tests)
testdiscr            = 407.16 sec*proc (111 tests)
testfilters          =  50.42 sec*proc (15 tests)
testfit              =   3.19 sec*proc (4 tests)
testintegration      =  18.22 sec*proc (14 tests)
testinterpolation    =  66.79 sec*proc (25 tests)
testleaks            =  14.61 sec*proc (16 tests)
testls               =   2.55 sec*proc (3 tests)
testmaterial         =   0.80 sec*proc (2 tests)
testmath             =   0.88 sec*proc (2 tests)
testmesh             =  39.44 sec*proc (26 tests)
testmodels           =   2.89 sec*proc (2 tests)
testopt              =   2.79 sec*proc (4 tests)
testpde              =  10.05 sec*proc (4 tests)
testpoly             =  29.71 sec*proc (18 tests)
testts               =   9.11 sec*proc (7 tests)
testvf               =  61.55 sec*proc (38 tests)

Total Test time (real) = 449.45 sec

The following tests did not run:
	188 - feelpp_test_space_0d-np-6 (Skipped)
	189 - feelpp_test_space_0d-np-1 (Skipped)
	301 - feelpp_test_bdf3-np-1 (Skipped)
	310 - feelpp_test_laplacianv-np-6 (Skipped)
	311 - feelpp_test_laplacianv-np-1 (Skipped)
	312 - feelpp_test_laplacian-np-6 (Skipped)
	313 - feelpp_test_laplacian-np-1 (Skipped)
	314 - feelpp_test_laplaciant-np-6 (Skipped)
	315 - feelpp_test_laplaciant-np-1 (Skipped)
	326 - feelpp_test_convolve-np-6 (Skipped)

The following tests FAILED:
	 41 - feelpp_test_serialization-np-6 (Failed)
	 42 - feelpp_test_serialization-np-1 (Failed)
	 54 - feelpp_test_vector-np-6 (Failed)
	 55 - feelpp_test_vector-np-1 (Failed)
	111 - feelpp_test_immultiscale-np-6 (Failed)
	112 - feelpp_test_immultiscale-np-1 (Failed)
	125 - feelpp_test_med-np-1 (Failed)
	228 - feelpp_test_projector-np-6 (Failed)
	272 - feelpp_test_productspaces-np-6 (Failed)
	282 - feelpp_test_eim-np-1 (Failed)
	283 - feelpp_test_eim_grepl-np-1 (Failed)
	284 - feelpp_test_eim_composite-np-1 (Failed)
	291 - feelpp_test_db-np-6 (Failed)
	292 - feelpp_test_db-np-1 (Failed)
	318 - feelpp_test_inner_curl-np-6 (Failed)
	319 - feelpp_test_inner_curl-np-1 (Not Run)
	354 - feelpp_test_solve_leak-np-6 (Failed)
Errors while running CTest
```

**Comment by prudhomm** [comment]
`test_serialization` crashes in Release but runs file in Debug.

```
ctest -R serializa
Test project /home/prudhomm/scratch/feelpp/dyn.clang.debug/testsuite/feelcore
    Start 41: feelpp_test_serialization-np-6
1/2 Test #41: feelpp_test_serialization-np-6 ...   Passed    2.00 sec
    Start 42: feelpp_test_serialization-np-1
2/2 Test #42: feelpp_test_serialization-np-1 ...   Passed    1.52 sec

100% tests passed, 0 tests failed out of 2

Label Time Summary:
testcore    =   3.52 sec*proc (2 tests)

Total Test time (real) =   3.53 sec
```

**Comment by prudhomm** [comment]
@vincentchabannes the PR is ready to be merged in dvelop

**Comment by prudhomm** [comment]
the crb/eim never wok for me but otherwise yes

**Comment by prudhomm** [comment]
no I don't work on atlas, too slow

**Comment by prudhomm** [comment]
the test failures are related to the current PR. the last issue was with `feelpp_test_vector` which is fixed

**Comment by vincentchabannes** [comment]
too slow? it's quite fast on a node. If you work on 4FastSim, there is a bug with Petsc installed by ubuntu (Gasm doesn't work)

**Comment by prudhomm** [comment]
yes but to do this kind of work I would take a node 24h/24 7j/7. I don t think it is acceptable.

**Comment by prudhomm** [comment]
very strange anyway because they don't crash or timeout on `cemosis.feelpp.org`

**Comment by vincentchabannes** [comment]
the first error that I see are `memory access violation` or `MPI_ERR_COMM: invalid communicator`

**Comment by prudhomm** [comment]
I have this for example: 
```
ctest -R mover
Test project /home/prudhomm/scratch/feelpp/dyn.clang.release/testsuite/feelmesh
    Start 21: feelpp_test_meshmover-np-6
1/2 Test #21: feelpp_test_meshmover-np-6 .......   Passed    2.71 sec
    Start 22: feelpp_test_meshmover-np-1
2/2 Test #22: feelpp_test_meshmover-np-1 .......   Passed    2.63 sec

100% tests passed, 0 tests failed out of 2

Label Time Summary:
testmesh    =   5.34 sec*proc (2 tests)

Total Test time (real) =   5.34 sec
```

**Comment by prudhomm** [comment]
@vincentchabannes I just re-run the tests above on `cemosis.feelpp.org`. I use clang6 in Release mode. I don't see anything specific with my setting. anything particular on atlas?

**Comment by prudhomm** [comment]
@vincentchabannes could you provide a backtrace even in Release mode to get an idea?

**Comment by prudhomm** [comment]
the communicator error could indeed be related to the changes I made in the `WorldComm` (#1205) but I don't see why it would break on one machine but not the other. 
Is it a clean rebuild?

**Comment by vincentchabannes** [comment]
yes, it's a clean build. I use the feelpp.profile and the develop branch with the testsuite is ok

**Comment by prudhomm** [comment]
@vincentchabannes by the way you may have noticed that the toolboxes build cleanly in `feature/ypthon` (see also buildkite). I removed a lot of warnings

**Comment by prudhomm** [comment]
@vincentchabannes  here is the status on Atlas:
```
The following tests did not run:
	187 - feelpp_test_space_0d-np-6 (Skipped)
	188 - feelpp_test_space_0d-np-1 (Skipped)
	300 - feelpp_test_bdf3-np-1 (Skipped)
	309 - feelpp_test_laplacianv-np-6 (Skipped)
	310 - feelpp_test_laplacianv-np-1 (Skipped)
	311 - feelpp_test_laplacian-np-6 (Skipped)
	312 - feelpp_test_laplacian-np-1 (Skipped)
	313 - feelpp_test_laplaciant-np-6 (Skipped)
	314 - feelpp_test_laplaciant-np-1 (Skipped)
	325 - feelpp_test_convolve-np-6 (Skipped)

The following tests FAILED:
	 41 - feelpp_test_serialization-np-6 (Failed)
	 42 - feelpp_test_serialization-np-1 (OTHER_FAULT)
	111 - feelpp_test_immultiscale-np-6 (Failed)
	112 - feelpp_test_immultiscale-np-1 (Failed)
	282 - feelpp_test_eim_grepl-np-1 (Timeout)
	283 - feelpp_test_eim_composite-np-1 (Failed)
	317 - feelpp_test_inner_curl-np-6 (Failed)
	318 - feelpp_test_inner_curl-np-1 (Not Run)
Errors while running CTest
```

**Comment by vincentchabannes** [comment]
@prudhomm it's ok for me

**Comment by prudhomm** [comment]
@vincentchabannes I am going to implement #1208 also in #930.

**Comment by vincentchabannes** [comment]
@prudhomm it's now quite urgent to merge this branch, this has a large impact for other developments.
Currently, the cmake process is broken (with crb app)

**Comment by prudhomm** [comment]
#930 is _urgent_ for mso4sc and v0.106

**Comment by prudhomm** [comment]
we need to report during the F2F meeting about the WP4 dev (sept 13)

**Comment by vincentchabannes** [comment]
Review and check your next changes come difficult if you continue in this branch without merge before. What do you think

**Comment by prudhomm** [comment]
I updated locally the buildkite process to reflect the directory layout. Once it is working properly we can merge and then the bigger reorganization will be applied

**Comment by prudhomm** [comment]
@vincentchabannes you didn't comment on having feelpp-toolboxes and feelpp-mor in their own repo

**Comment by vincentchabannes** [comment]
@prudhomm I am agree to move in another repo, but not now. We need to merge all other work before (in particular levelset )

**Comment by prudhomm** [comment]
yes of course. there is also the ls-contact branch and quite a few other ones

**Comment by prudhomm** [comment]
@vincentchabannes it is all good now. the issue with mor was due to files in git that were also in .gitignore and when I moved to mor, the .gitignore took over and the files (.xml.in and .cfg) were not in git anymore. It is fixed now. 
The next issues were simply that we have to create the docker repo in Docker hub for feelpp-pyfeelpp-mor, feelpp-mor and feelpp-pyfeelpp-toolboxes.

**Comment by prudhomm** [comment]
see for example https://buildkite.com/feelpp/feelpp/builds/2614.

there is still a slight issue with the make install in `pyfeelpp`: we recompile everything each time. This should be relatively easy to fix

**Comment by prudhomm** [comment]
This is the first part of the merge, #930 is soon finished, #1028 requires the libfeelpp component will required quite specific developments

**Pull request merged**
