### PR TITLE
Feature/optimize

### PR DESCRIPTION
**Pull request by prudhomm**
implements
 - #787 
 - #771 
 - summary json file parseable, readable
 - reorganize application directory handling
   - define `Environment::appRepository()`, `Environment::logsRepository()`, `Environment::exportsRepository()`, `Environment::exprsRepository()`
   - enable removing appRespository() (--rm)
   - enable removing logs (--rmlogs)
   - add  `Environment::{start,stop}Logging()` and deal with directory change 
 - #826

### CODE REVIEW

**Comment by prudhomm** [comment]
Here is the current status of the testsuite. 
Note that `--rm` is used to clean up directory after test is run
```
95% tests passed, 17 tests failed out of 335

Label Time Summary:
testalg              =  13.32 sec (22 tests)
testcore             = 310.88 sec (36 tests)
testcrb              =  31.43 sec (11 tests)
testdiscr            = 815.61 sec (94 tests)
testfilters          =  78.99 sec (12 tests)
testfit              =   1.48 sec (4 tests)
testintegration      =  25.37 sec (14 tests)
testinterpolation    =  97.12 sec (25 tests)
testleaks            =  11.65 sec (16 tests)
testls               =   1.30 sec (3 tests)
testmaterial         =   0.60 sec (2 tests)
testmath             =   0.50 sec (2 tests)
testmesh             =  42.70 sec (24 tests)
testmodels           =   1.61 sec (2 tests)
testopt              =   0.44 sec (2 tests)
testpde              =  32.16 sec (4 tests)
testpoly             =  30.07 sec (18 tests)
testts               =   3.18 sec (5 tests)
testvf               = 730.81 sec (38 tests)

Total Test time (real) = 1147.94 sec

The following tests FAILED:
	 32 - feelpp_test_worldcomm-np-6 (Timeout)
	 55 - feelpp_test_matrix_block-np-1 (Failed)
	218 - feelpp_test_submesh-np-6 (Timeout)
	251 - feelpp_test_element0D-np-6 (Failed)
	252 - feelpp_test_element0D-np-1 (Failed)
	266 - feelpp_test_bdf2-np-6 (Failed)
	267 - feelpp_test_bdf2-np-1 (Failed)
	268 - feelpp_test_bdf3-np-1 (Failed)
	275 - feelpp_test_laplacianv-np-6 (Failed)
	276 - feelpp_test_laplacianv-np-1 (Failed)
	277 - feelpp_test_laplacian-np-6 (Failed)
	278 - feelpp_test_laplacian-np-1 (Failed)
	279 - feelpp_test_laplaciant-np-6 (Timeout)
	280 - feelpp_test_laplaciant-np-1 (Failed)
	291 - feelpp_test_convolve-np-6 (Timeout)
	332 - feelpp_test_nofeel_interpolator-np-6 (Failed)
	333 - feelpp_test_nofeel_interpolator-np-1 (Failed)
Errors while running CTest

```

**Comment by Trophime** [comment]
We should check that gmsh actually support MED in the code
to issue an error when trying to load a MED file if MED is or not supported. 
Otherwise we would end up with strange errors as gmsh (without med support) do nothing when loading a MED file...

Same apply to CGNS

**Comment by prudhomm** [comment]
@Trophime you mean checking the status integer returned by GModel ?

**Comment by Trophime** [comment]
@prudhomm CGNS support in Gmsh id not fully functional. I think we'd better not support CGNS through  gmsh.

**Comment by Trophime** [comment]
I will cherry pick my latest commit to optimize-mesh branch.

**Comment by Trophime** [comment]
I guess we can remove loadMeshmsh.hpp and loadMEDmesh.hpp...

**Comment by Trophime** [comment]
Travis FTBS since it build the minimal version.
Just uploaded the merge from the cherry-pick on feature/optimise-mesh branch

**Pull request merged**
