### PR TITLE
CMake: include GMSH directories BEFORE (prepend)

### PR DESCRIPTION
**Pull request by metivett**
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/feelpp/feelpp/pulls) for the same change?
- [X] Have you added an explanation of what your changes do and why you'd like us to include them?
-----

This PR provides a quick fix for the compilation issue on case insensitive OS (#1256), related to GMSH headers includes.
More advanced fixes involve more thorough analysis and accurate specifications for the includes, as the conflicting `context.h` header coming from both PYTHON and GMSH libraries should not be mixed. However solving the conflicting case (when the file requires both PYTHON's and GMSH's context.h files) is still under debate...

### CODE REVIEW

**Comment by vincentchabannes** [comment]
this is already tested, no problem with this pr

**Comment by prudhomm** [comment]
what do you mean? it is already in develop ?

**Comment by vincentchabannes** [comment]
No, but I have tested (atlas, macos and docker) this one before send it the patch to @metivett .
And buildkite has already compiled the branch feature/ls without any problem.

**Comment by prudhomm** [comment]
my concern is that there might be side effects with python. if you say it is good then, then let's go

**Comment by vincentchabannes** [comment]
The issue is only macos with homebrew. If a problem appears we can limit this change to this architecture.
In the future, I would like to hide the gmsh include in the feel++ headers and use only in some source files. It's quite easy to do that with cmake, but it requires a recent version, so I wait

**Pull request merged**
