### PR TITLE
Prudhomm/issue1626

### PR DESCRIPTION
**Pull request by prudhomm**
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/feelpp/feelpp/pulls) for the same change?
- [X] Have you added an explanation of what your changes do and why you'd like us to include them?
- [X] Have you written new tests for your changes?
- [X] Have you successfully run the Feel++ testsuite with your changes locally?
- [ ] Have you written Doxygen comments in your contribution ?

-----

implements

- #1626 Review, update python scripts and add tests
- #1628 move toolboxes cases in subdirectory cases
- #1646 add support for petsc4py

### CODE REVIEW

**Comment by vincentchabannes** [comment]
@prudhomm some tests fails (hdg_poisson-quarter-turn*), see [here](https://buildkite.com/feelpp/feelpp/builds/3848#032ae9b2-2379-4beb-9991-c6d4e7217ff4/4247-4366).
Also, I noticed that there are some changes in the example of cahn-hillard. It's normal or a mistake?

**Comment by prudhomm** [comment]
> @prudhomm some tests fails (hdg_poisson-quarter-turn*), see [here](https://buildkite.com/feelpp/feelpp/builds/3848#032ae9b2-2379-4beb-9991-c6d4e7217ff4/4247-4366).
indeed I imported the work by @romainhild @thomas-saigre  but it seems that something is not quite right with the hdg tests

> Also, I noticed that there are some changes in the example of cahn-hillard. It's normal or a mistake?
probably a mistake

**Comment by prudhomm** [comment]
```
ctest -R _toolbox_
Test project /home/prudhomm/Devel/feelpp/build-cpp17-toolboxes-mor-release-nosws-nodoxygen-nomatplot/toolboxes
      Start  1: feelpp_toolbox_coefficientformpdes-ThermalBridgesENISO10211_case2-np-6
 1/50 Test  #1: feelpp_toolbox_coefficientformpdes-ThermalBridgesENISO10211_case2-np-6 ...............   Passed    3.96 sec
      Start  2: feelpp_toolbox_coefficientformpdes-ThermalBridgesENISO10211_case2-np-1
 2/50 Test  #2: feelpp_toolbox_coefficientformpdes-ThermalBridgesENISO10211_case2-np-1 ...............   Passed    4.76 sec
      Start  3: feelpp_toolbox_coefficientformpdes-ThermalBridgesENISO10211_case2_alternative-np-6
 3/50 Test  #3: feelpp_toolbox_coefficientformpdes-ThermalBridgesENISO10211_case2_alternative-np-6 ...   Passed    3.82 sec
      Start  4: feelpp_toolbox_coefficientformpdes-ThermalBridgesENISO10211_case2_alternative-np-1
 4/50 Test  #4: feelpp_toolbox_coefficientformpdes-ThermalBridgesENISO10211_case2_alternative-np-1 ...   Passed    5.61 sec
      Start  5: feelpp_toolbox_coefficientformpdes-heat_thermo2d-np-6
 5/50 Test  #5: feelpp_toolbox_coefficientformpdes-heat_thermo2d-np-6 ................................   Passed   12.16 sec
      Start  6: feelpp_toolbox_coefficientformpdes-heat_thermo2d-np-1
 6/50 Test  #6: feelpp_toolbox_coefficientformpdes-heat_thermo2d-np-1 ................................   Passed   14.35 sec
      Start  7: feelpp_toolbox_coefficientformpdes-heat_thermo2d_alternative-np-6
 7/50 Test  #7: feelpp_toolbox_coefficientformpdes-heat_thermo2d_alternative-np-6 ....................   Passed   29.26 sec
      Start  8: feelpp_toolbox_coefficientformpdes-heat_thermo2d_alternative-np-1
 8/50 Test  #8: feelpp_toolbox_coefficientformpdes-heat_thermo2d_alternative-np-1 ....................   Passed   59.61 sec
      Start  9: feelpp_toolbox_coefficientformpdes-ElectroMagnets_HL-31_H1-np-6
 9/50 Test  #9: feelpp_toolbox_coefficientformpdes-ElectroMagnets_HL-31_H1-np-6 ......................   Passed   10.63 sec
      Start 10: feelpp_toolbox_coefficientformpdes-ElectroMagnets_HL-31_H1-np-1
10/50 Test #10: feelpp_toolbox_coefficientformpdes-ElectroMagnets_HL-31_H1-np-1 ......................   Passed   19.80 sec
      Start 11: feelpp_toolbox_coefficientformpdes-bratu-np-6
11/50 Test #11: feelpp_toolbox_coefficientformpdes-bratu-np-6 ........................................   Passed    2.14 sec
      Start 12: feelpp_toolbox_coefficientformpdes-bratu-np-1
12/50 Test #12: feelpp_toolbox_coefficientformpdes-bratu-np-1 ........................................   Passed    2.09 sec
      Start 13: feelpp_toolbox_fluid-TurekHron-cfd1-P2P1G1-Newton-np-6
13/50 Test #13: feelpp_toolbox_fluid-TurekHron-cfd1-P2P1G1-Newton-np-6 ...............................   Passed    6.21 sec
      Start 14: feelpp_toolbox_fluid-TurekHron-cfd1-P2P1G1-Newton-np-1
14/50 Test #14: feelpp_toolbox_fluid-TurekHron-cfd1-P2P1G1-Newton-np-1 ...............................   Passed   10.61 sec
      Start 15: feelpp_toolbox_fluid-TurekHron-cfd2-P2P1G1-Newton-np-6
15/50 Test #15: feelpp_toolbox_fluid-TurekHron-cfd2-P2P1G1-Newton-np-6 ...............................   Passed    7.29 sec
      Start 16: feelpp_toolbox_fluid-TurekHron-cfd2-P2P1G1-Newton-np-1
16/50 Test #16: feelpp_toolbox_fluid-TurekHron-cfd2-P2P1G1-Newton-np-1 ...............................   Passed   13.14 sec
      Start 17: feelpp_toolbox_fluid-TurekHron-cfd1-P2P1G1-Picard-np-6
17/50 Test #17: feelpp_toolbox_fluid-TurekHron-cfd1-P2P1G1-Picard-np-6 ...............................   Passed    9.60 sec
      Start 18: feelpp_toolbox_fluid-TurekHron-cfd1-P2P1G1-Picard-np-1
18/50 Test #18: feelpp_toolbox_fluid-TurekHron-cfd1-P2P1G1-Picard-np-1 ...............................   Passed   16.76 sec
      Start 19: feelpp_toolbox_fluid-TurekHron-cfd2-P2P1G1-Picard-np-6
19/50 Test #19: feelpp_toolbox_fluid-TurekHron-cfd2-P2P1G1-Picard-np-6 ...............................   Passed   15.96 sec
      Start 20: feelpp_toolbox_fluid-TurekHron-cfd2-P2P1G1-Picard-np-1
20/50 Test #20: feelpp_toolbox_fluid-TurekHron-cfd2-P2P1G1-Picard-np-1 ...............................   Passed   30.15 sec
      Start 21: feelpp_toolbox_fluid-TurekHron-cfd1-P1P1G1-Newton-np-6
21/50 Test #21: feelpp_toolbox_fluid-TurekHron-cfd1-P1P1G1-Newton-np-6 ...............................   Passed    6.14 sec
      Start 22: feelpp_toolbox_fluid-TurekHron-cfd1-P1P1G1-Newton-np-1
22/50 Test #22: feelpp_toolbox_fluid-TurekHron-cfd1-P1P1G1-Newton-np-1 ...............................   Passed    9.93 sec
      Start 23: feelpp_toolbox_fluid-TurekHron-cfd1-transient-BDF2-np-6
23/50 Test #23: feelpp_toolbox_fluid-TurekHron-cfd1-transient-BDF2-np-6 ..............................   Passed   29.34 sec
      Start 24: feelpp_toolbox_fluid-TurekHron-cfd1-transient-BDF2-np-1
24/50 Test #24: feelpp_toolbox_fluid-TurekHron-cfd1-transient-BDF2-np-1 ..............................   Passed   58.99 sec
      Start 25: feelpp_toolbox_fluid-TurekHron-cfd2-transient-BDF2-np-6
25/50 Test #25: feelpp_toolbox_fluid-TurekHron-cfd2-transient-BDF2-np-6 ..............................   Passed   34.20 sec
      Start 26: feelpp_toolbox_fluid-TurekHron-cfd2-transient-BDF2-np-1
26/50 Test #26: feelpp_toolbox_fluid-TurekHron-cfd2-transient-BDF2-np-1 ..............................   Passed   71.94 sec
      Start 27: feelpp_toolbox_fluid-TurekHron-cfd1-transient-CN-np-6
27/50 Test #27: feelpp_toolbox_fluid-TurekHron-cfd1-transient-CN-np-6 ................................   Passed   32.29 sec
      Start 28: feelpp_toolbox_fluid-TurekHron-cfd1-transient-CN-np-1
28/50 Test #28: feelpp_toolbox_fluid-TurekHron-cfd1-transient-CN-np-1 ................................   Passed   73.63 sec
      Start 29: feelpp_toolbox_fluid-TurekHron-cfd2-transient-CN-np-6
29/50 Test #29: feelpp_toolbox_fluid-TurekHron-cfd2-transient-CN-np-6 ................................   Passed   48.80 sec
      Start 30: feelpp_toolbox_fluid-TurekHron-cfd2-transient-CN-np-1
30/50 Test #30: feelpp_toolbox_fluid-TurekHron-cfd2-transient-CN-np-1 ................................   Passed   98.12 sec
      Start 31: feelpp_toolbox_fluid-Pipe-Pressure-Stokes-np-6
31/50 Test #31: feelpp_toolbox_fluid-Pipe-Pressure-Stokes-np-6 .......................................   Passed    4.03 sec
      Start 32: feelpp_toolbox_fluid-Pipe-Pressure-Stokes-np-1
32/50 Test #32: feelpp_toolbox_fluid-Pipe-Pressure-Stokes-np-1 .......................................   Passed    3.47 sec
      Start 33: feelpp_toolbox_fluid-Pipe-Pressure-Navier-Stokes-np-6
33/50 Test #33: feelpp_toolbox_fluid-Pipe-Pressure-Navier-Stokes-np-6 ................................   Passed    3.55 sec
      Start 34: feelpp_toolbox_fluid-Pipe-Pressure-Navier-Stokes-np-1
34/50 Test #34: feelpp_toolbox_fluid-Pipe-Pressure-Navier-Stokes-np-1 ................................   Passed    3.61 sec
      Start 35: feelpp_toolbox_solid-TurekHron-csm1-np-6
35/50 Test #35: feelpp_toolbox_solid-TurekHron-csm1-np-6 .............................................   Passed    7.23 sec
      Start 36: feelpp_toolbox_solid-TurekHron-csm1-np-1
36/50 Test #36: feelpp_toolbox_solid-TurekHron-csm1-np-1 .............................................   Passed    5.77 sec
      Start 37: feelpp_toolbox_solid-TurekHron-csm2-np-6
37/50 Test #37: feelpp_toolbox_solid-TurekHron-csm2-np-6 .............................................   Passed    7.38 sec
      Start 38: feelpp_toolbox_solid-TurekHron-csm2-np-1
38/50 Test #38: feelpp_toolbox_solid-TurekHron-csm2-np-1 .............................................   Passed    4.51 sec
      Start 39: feelpp_toolbox_hdg_poisson-quarter-turn-2d-np-6
39/50 Test #39: feelpp_toolbox_hdg_poisson-quarter-turn-2d-np-6 ......................................   Passed    6.43 sec
      Start 40: feelpp_toolbox_hdg_poisson-quarter-turn-2d-np-1
40/50 Test #40: feelpp_toolbox_hdg_poisson-quarter-turn-2d-np-1 ......................................   Passed    1.18 sec
      Start 41: feelpp_toolbox_hdg_poisson-quarter-turn-2d-int-np-6
41/50 Test #41: feelpp_toolbox_hdg_poisson-quarter-turn-2d-int-np-6 ..................................   Passed    4.53 sec
      Start 42: feelpp_toolbox_hdg_poisson-quarter-turn-2d-int-np-1
42/50 Test #42: feelpp_toolbox_hdg_poisson-quarter-turn-2d-int-np-1 ..................................   Passed    1.54 sec
      Start 43: feelpp_toolbox_hdg_poisson-quarter-turn-3d-np-6
43/50 Test #43: feelpp_toolbox_hdg_poisson-quarter-turn-3d-np-6 ......................................   Passed   12.32 sec
      Start 44: feelpp_toolbox_hdg_poisson-quarter-turn-3d-np-1
44/50 Test #44: feelpp_toolbox_hdg_poisson-quarter-turn-3d-np-1 ......................................   Passed    7.54 sec
      Start 45: feelpp_toolbox_hdg_poisson-quarter-turn-3d-int-np-6
45/50 Test #45: feelpp_toolbox_hdg_poisson-quarter-turn-3d-int-np-6 ..................................   Passed    9.67 sec
      Start 46: feelpp_toolbox_hdg_poisson-quarter-turn-3d-int-np-1
46/50 Test #46: feelpp_toolbox_hdg_poisson-quarter-turn-3d-int-np-1 ..................................   Passed   16.10 sec
      Start 47: feelpp_toolbox_heat-ThermalBridgesENISO10211_case2-np-6
47/50 Test #47: feelpp_toolbox_heat-ThermalBridgesENISO10211_case2-np-6 ..............................   Passed    2.07 sec
      Start 48: feelpp_toolbox_heat-ThermalBridgesENISO10211_case2-np-1
48/50 Test #48: feelpp_toolbox_heat-ThermalBridgesENISO10211_case2-np-1 ..............................   Passed    3.01 sec
      Start 49: feelpp_toolbox_python-tests
49/50 Test #49: feelpp_toolbox_python-tests ..........................................................   Passed   11.93 sec
      Start 50: feelpp_toolbox_python-tests-mpi
50/50 Test #50: feelpp_toolbox_python-tests-mpi ......................................................   Passed    9.14 sec

100% tests passed, 0 tests failed out of 50

Total Test time (real) = 866.54 sec
```

**Comment by prudhomm** [comment]
pythojn tests fore feelpp are here

**Comment by prudhomm** [comment]
https://buildkite.com/feelpp/feelpp/builds/3855

**Comment by prudhomm** [comment]
python toolbox tests are fully operational including in parallel
```
The following tests passed:
        feelpp_toolbox_python-tests
        feelpp_toolbox_python-tests-mpi

100% tests passed, 0 tests failed out of 2

Total Test time (real) =  81.64 sec
```

**Pull request merged**
