### PR TITLE
Tests 1374 1422

### PR DESCRIPTION
**Pull request by romainhild**
add tests for issues #1422 and #1374

### CODE REVIEW

**Comment by vincentchabannes** [comment]
@romainhild I have finished, could you check if it's ok for you?

**Comment by romainhild** [comment]
@vincentchabannes no I have another error:
```
integrator.hpp:4622] Check failed: false [assembleWithRelationDifferentMeshType<LinearForm,MESH_FACES>] : isConnectedTo1 not yet implement
```

It comes from the assembly of the Neumann right hand side.
```
integrate( _range=markedfaces(M_Wh), marker), _expr = id(l)*expr);
```
where `M_Wh` is a discontinuous space on the elements of the mesh, while `l` is an element of a discontinuous space on the faces of the support of `M_Wh`.

**Comment by prudhomm** [comment]
Ok this case should not be too hard to fix. 
we didn't need that before with standard meshes. but with range based mesh we can definitely be in this situation

**Comment by vincentchabannes** [comment]
indeed, this case is not yet implemented. We just need to adapat my wok to linearform, not so hard but need a little but effort to avoid to have duplicated code

**Comment by romainhild** [comment]
this branch will be merge in #1439, so we can close this pull request

**Comment by vincentchabannes** [comment]
I prefer to merge the pull request, it's not only related to hdg, but a general fix of linear/bilinear form with mesh support

**Comment by vincentchabannes** [comment]
finally, we don't apply the merge, there are some change sin hdg toolboxes which can break develop branch

**Comment by prudhomm** [comment]
which PR are you talking about @vincentchabannes? #1423 ? or #1439?
the HDG changes are in #1439 no ?

**Comment by romainhild** [comment]
no there is also some changes here, it is my fault.
But this branch has just been merged in #1439 which is ready to be reviewed.

**Comment by romainhild** [comment]
not in this branch but in #1439 I fixed couplemixedpoisson.

**Comment by prudhomm** [comment]
Aarggh why the mess ?

**Comment by prudhomm** [comment]
so this PR should be deleted ?

**Comment by romainhild** [comment]
well it is my fault, I shouldn't have add the hdg changes here, but it was to find the right test to put in space_on_range.
So yes I think this PR should be deleted and all review be done in #1439

**Comment by prudhomm** [comment]
@romainhild could you apply the changes I asked in this review for the other PR ?

**Comment by prudhomm** [comment]
I will review the rest of #1439  once it is done, let me know

**Comment by romainhild** [comment]
for the test messages no problem, for the rest maybe @vincentchabannes will want to check

**Comment by romainhild** [comment]
the boost messages are in #1439 
I close this PR.

**Pull request closed without merging**
