### PR TITLE
Feature/prec adapt ns

### PR DESCRIPTION
**Pull request by prudhomm**
adapt preconditioner blockns to spatially changing viscosity/density
 - #460  (pcd,pmm)
 - #496 (simple preconditioner)
 - #685 pre/post function calls in ksp solve (useful for solution up to a constant)
 - #688 helper function : vec(Vec,DataMap)

### CODE REVIEW

**Comment by prudhomm** [comment]
@vincentchabannes @metivett I would like to merge this PR
here are the results of the testsuite

```
91% tests passed, 25 tests failed out of 288                                                                                                                                                                
                                                                                                                                                                                                            
Label Time Summary:                                                                                                                                                                                         
testalg              = 322.99 sec                                                                                                                                                                           
testcore             =  29.69 sec                                                                                                                                                                           
testcrb              = 794.91 sec                                                                                                                                                                           
testdiscr            = 1300.71 sec                                                                                                                                                                          
testfilters          = 133.16 sec                                                                                                                                                                           
testintegration      = 345.98 sec                                                                                                                                                                           
testinterpolation    = 885.64 sec                                                                                                                                                                           
testleaks            =  34.29 sec                                                                                                                                                                           
testls               =   5.58 sec                                                                                                                                                                           
testmaterial         =   1.93 sec                                                                                                                                                                           
testmath             =   1.93 sec                                                                                                                                                                           
testmesh             =  26.00 sec                                                                                                                                                                           
testmodels           =   1.85 sec                                                                                                                                                                           
testopt              =   1.42 sec                                                                                                                                                                           
testpoly             = 101.31 sec                                                                                                                                                                           
testts               = 306.58 sec                                                                                                                                                                           
testvf               = 561.25 sec                                                                                                                                                                           
                                                                                                                                                                                                            
Total Test time (real) = 992.08 sec                                                                                                                                                                         
                                                                                                                                                                                                            
The following tests FAILED:                                                                                                                                                                                 
         19 - test_boostmpi (Failed)                                                                                                                                                                        
         47 - feelpp_test_eigenmode-np-6 (Timeout)                                                                                                                                                          
         48 - feelpp_test_eigenmode-np-1 (Failed)                                                                                                                                                           
         73 - feelpp_test_im-np-6 (Failed)                                                                                                                                                                  
         74 - feelpp_test_im-np-1 (Failed)                                                                                                                                                                  
        105 - feelpp_test_operatorinterpolation-np-6 (Timeout)                                                                                                                                              
        107 - feelpp_test_hypercubeinterpolation-np-6 (Timeout)                                                                                                                                             
        134 - feelpp_test_integration_relatedmesh-np-6 (Timeout)                                                                                                                                            
        145 - feelpp_test_functionallinearfree-np-6 (Failed)                                                                                                                                                
        157 - feelpp_test_hdiv3D_oneelt-np-1 (Failed)                                                                                                                                                       
        164 - feelpp_test_hcurl3D_oneelt-np-1 (Failed)                                                                                                                                                      
        171 - feelpp_test_lift-np-6 (Failed)                                                                                                                                                                
        179 - feelpp_test_mixed-np-6 (Failed)                                                                                                                                                               
        202 - feelpp_test_multiscaleimage-np-6 (Timeout)                                                                                                                                                    
        203 - feelpp_test_multiscaleimage-np-1 (Timeout)                                                                                                                                                    
        215 - feelpp_test_eigs-np-6 (Failed)                                                                                                                                                                
        225 - feelpp_test_eim-np-6 (Timeout)                                                                                                                                                                
        227 - feelpp_test_eim_grepl-np-6 (Timeout)                                                                                                                                                          
        228 - feelpp_test_eim_grepl-np-1 (Timeout)                                                                                                                                                          
        229 - feelpp_test_eim_composite-np-6 (Timeout)                                                                                                                                                      
        239 - feelpp_test_bdf3-np-6 (Timeout)                                                                                                                                                               
        240 - feelpp_test_bdf3-np-1 (Failed)                                                                                                                                                                
        251 - feelpp_test_msi-np-6 (Failed)                                                                                                                                                                 
        261 - feelpp_test_convolve-np-6 (Timeout)                                                                                                                                                           
        287 - feelpp_test_extender_from_interface-np-6 (Failed)          
```
I am still checking a few things but could you check that the changes are ok for you?
in particular there is a change in `MatrixPetsc::close() ` using `MatAssembled` that needs to be checked.

**Comment by prudhomm** [comment]
@LANTZT (@vincentchabannes) could you run one of the benchmarks eg 2D CFD Turek to ensure that we get the same results with this branch (feature/prec-adapt-ns) as with develop ?

**Comment by LANTZT** [comment]
@prudhomm Ok, I'm on it

**Comment by LANTZT** [comment]
@prudhomm I have some difficulties to compile the feature/prec-adapt-ns branch to realize the benchmark test.
Here is the error :

```
/home/u2/lantz/feelpp/feel/feelalg/backendpetsc.cpp:51:24: error:
      no matching constructor for initialization of
      'vector_ptrtype' (aka 'shared_ptr<vector_type>')
        vector_ptrtype vx( vec( x, b->dataMap() ) );
```

It repeat 4 times ( 2 times in feelpp_petsc_pre_solve and 2 times in feelpp_petsc_post_solve )

**Comment by prudhomm** [comment]
@LANTZT I look at this. what did you compile ?

**Comment by LANTZT** [comment]
@prudhomm After remake a new build folder for this branch, I just do a `make -j 16` into `applications/models/fluid`.

**Comment by prudhomm** [comment]
@LANTZT i could compile all the codes in applicatios/models with this branch without problems
do you have the latest version of this branch ?

**Comment by LANTZT** [comment]
@prudhomm I think so, I did a `git pull` before the test.
I will retry today to see if it's working for me

**Comment by LANTZT** [comment]
@prudhomm This time, I totally recloned feelpp, placed me in `feature/prec-adapt-ns', configured a new build folder and started compiling in `applications/models` with a `make -j 20`.
And I still have the same errors ...

**Comment by LANTZT** [comment]
@prudhomm I'm think I found why it didn't work for me
In fact, I try with `feelpp.profile` loaded and it seems to work much better than before.
My bad !

**Comment by prudhomm** [comment]
ok let me know how it went

**Comment by LANTZT** [comment]
Here are results from one CSM2 benchmark :

branch | x dips | y disp
------------ | -------------  | -------------
develop | -4.5897182353975589e-04 |  -1.6765621709080067e-02
feature/prec-adapt-ns | -4.5897140871607842e-04 | -1.6765613422187312e-02

It seems good for me, I'm on a other test with CFD2 this time.

**Comment by prudhomm** [comment]
Ok thanks

**Comment by LANTZT** [comment]
@prudhomm After some troubles ( mistakes from my side ), these are results from a CFD2 benchmark :

branch | drag | lift
------------ | -------------  | -------------
develop | -1.3532283212844581e+02 | -1.0442497811252057e+01
feature/prec-adapt-ns | -1.3532283212844584e+02 | -1.0442497811251627e+01

**Comment by prudhomm** [comment]
Ok good :)
thx for the trouble

**Pull request merged**
