### PR TITLE
Feature/quad

### PR DESCRIPTION
**Pull request by prudhomm**
implements dynamic quadrature
- #571

### CODE REVIEW

**Comment by prudhomm** [comment]
@vincentchabannes dynamic quadratures branch, sync'ed with develop. A few tests are failing at the moment, I am fixing 
feel free to have a look.
merge will occur when all tests run properly.

**Comment by vincentchabannes** [comment]
@prudhomm did you push all your work? I have errors in the compilation of lib feelpp

**Comment by prudhomm** [comment]
Indeed I have quite a few changes not yet committed. I am currently fighting with crashes in the mesh data strcuture

**Comment by prudhomm** [comment]
@vincentchabannes I finally managed to find the issue with the branch. I got bitten back by a nasty const_cast and didn't fail to compile and which was corrupting the mesh elements.
I have started cleaning up a bit and fix the interface.

**Comment by prudhomm** [comment]
here is  the quickstart testsuite (quite encouraging):
```
 2018-05-23 05:57:33 ⌚  sd-135989 in ~/scratch/feelpp/2.clang6.debug/quickstart
○ → ctest -R .
Test project /home/prudhomm/scratch/feelpp/2.clang6.debug/quickstart
      Start  1: feelpp_qs_laplacian_2d-circle-dirichlet-np-6
 1/40 Test  #1: feelpp_qs_laplacian_2d-circle-dirichlet-np-6 ...............   Passed    2.55 sec
      Start  2: feelpp_qs_laplacian_2d-circle-dirichlet-np-1
 2/40 Test  #2: feelpp_qs_laplacian_2d-circle-dirichlet-np-1 ...............   Passed    2.75 sec
      Start  3: feelpp_qs_laplacian_2d-circle-robin-np-6
 3/40 Test  #3: feelpp_qs_laplacian_2d-circle-robin-np-6 ...................   Passed    3.35 sec
      Start  4: feelpp_qs_laplacian_2d-circle-robin-np-1
 4/40 Test  #4: feelpp_qs_laplacian_2d-circle-robin-np-1 ...................   Passed    2.17 sec
      Start  5: feelpp_qs_laplacian_2d-circle-all-np-6
 5/40 Test  #5: feelpp_qs_laplacian_2d-circle-all-np-6 .....................   Passed    3.32 sec
      Start  6: feelpp_qs_laplacian_2d-circle-all-np-1
 6/40 Test  #6: feelpp_qs_laplacian_2d-circle-all-np-1 .....................   Passed    2.93 sec
      Start  7: feelpp_qs_laplacian_2d-triangle-oneelt-1-np-6
 7/40 Test  #7: feelpp_qs_laplacian_2d-triangle-oneelt-1-np-6 ..............   Passed    1.64 sec
      Start  8: feelpp_qs_laplacian_2d-triangle-oneelt-1-np-1
 8/40 Test  #8: feelpp_qs_laplacian_2d-triangle-oneelt-1-np-1 ..............   Passed    1.48 sec
      Start  9: feelpp_qs_laplacian_2d-triangle-oneelt-x+y-np-6
 9/40 Test  #9: feelpp_qs_laplacian_2d-triangle-oneelt-x+y-np-6 ............   Passed    2.14 sec
      Start 10: feelpp_qs_laplacian_2d-triangle-oneelt-x+y-np-1
10/40 Test #10: feelpp_qs_laplacian_2d-triangle-oneelt-x+y-np-1 ............   Passed    1.64 sec
      Start 11: feelpp_qs_laplacian_2d-triangle-oneelt-x^2+y^2-np-6
11/40 Test #11: feelpp_qs_laplacian_2d-triangle-oneelt-x^2+y^2-np-6 ........   Passed    2.15 sec
      Start 12: feelpp_qs_laplacian_2d-triangle-oneelt-x^2+y^2-np-1
12/40 Test #12: feelpp_qs_laplacian_2d-triangle-oneelt-x^2+y^2-np-1 ........   Passed    1.39 sec
      Start 13: feelpp_qs_laplacian_2d-triangle-1-np-6
13/40 Test #13: feelpp_qs_laplacian_2d-triangle-1-np-6 .....................   Passed    2.04 sec
      Start 14: feelpp_qs_laplacian_2d-triangle-1-np-1
14/40 Test #14: feelpp_qs_laplacian_2d-triangle-1-np-1 .....................   Passed    1.81 sec
      Start 15: feelpp_qs_laplacian_2d-triangle-x+y-np-6
15/40 Test #15: feelpp_qs_laplacian_2d-triangle-x+y-np-6 ...................   Passed    2.51 sec
      Start 16: feelpp_qs_laplacian_2d-triangle-x+y-np-1
16/40 Test #16: feelpp_qs_laplacian_2d-triangle-x+y-np-1 ...................   Passed    2.11 sec
      Start 17: feelpp_qs_laplacian_2d-triangle-x^2+y^2-np-6
17/40 Test #17: feelpp_qs_laplacian_2d-triangle-x^2+y^2-np-6 ...............   Passed    2.53 sec
      Start 18: feelpp_qs_laplacian_2d-triangle-x^2+y^2-np-1
18/40 Test #18: feelpp_qs_laplacian_2d-triangle-x^2+y^2-np-1 ...............   Passed    2.34 sec
      Start 19: feelpp_qs_laplacian_3d-tetrahedron-oneelt-cst-np-6
19/40 Test #19: feelpp_qs_laplacian_3d-tetrahedron-oneelt-cst-np-6 .........   Passed    3.34 sec
      Start 20: feelpp_qs_laplacian_3d-tetrahedron-oneelt-cst-np-1
20/40 Test #20: feelpp_qs_laplacian_3d-tetrahedron-oneelt-cst-np-1 .........   Passed    2.95 sec
      Start 21: feelpp_qs_laplacian_3d-tetrahedron-oneelt-linear-np-6
21/40 Test #21: feelpp_qs_laplacian_3d-tetrahedron-oneelt-linear-np-6 ......   Passed    3.24 sec
      Start 22: feelpp_qs_laplacian_3d-tetrahedron-oneelt-linear-np-1
22/40 Test #22: feelpp_qs_laplacian_3d-tetrahedron-oneelt-linear-np-1 ......   Passed    3.57 sec
      Start 23: feelpp_qs_laplacian_3d-tetrahedron-oneelt-quadratic-np-6
23/40 Test #23: feelpp_qs_laplacian_3d-tetrahedron-oneelt-quadratic-np-6 ...   Passed    3.37 sec
      Start 24: feelpp_qs_laplacian_3d-tetrahedron-oneelt-quadratic-np-1
24/40 Test #24: feelpp_qs_laplacian_3d-tetrahedron-oneelt-quadratic-np-1 ...   Passed    3.33 sec
      Start 25: feelpp_qs_laplacian_3d-tetrahedron-cst-np-6
25/40 Test #25: feelpp_qs_laplacian_3d-tetrahedron-cst-np-6 ................   Passed   10.39 sec
      Start 26: feelpp_qs_laplacian_3d-tetrahedron-cst-np-1
26/40 Test #26: feelpp_qs_laplacian_3d-tetrahedron-cst-np-1 ................   Passed   23.50 sec
      Start 27: feelpp_qs_laplacian_3d-tetrahedron-linear-np-6
27/40 Test #27: feelpp_qs_laplacian_3d-tetrahedron-linear-np-6 .............   Passed   10.80 sec
      Start 28: feelpp_qs_laplacian_3d-tetrahedron-linear-np-1
28/40 Test #28: feelpp_qs_laplacian_3d-tetrahedron-linear-np-1 .............   Passed   25.82 sec
      Start 29: feelpp_qs_laplacian_3d-tetrahedron-quadratic-np-6
29/40 Test #29: feelpp_qs_laplacian_3d-tetrahedron-quadratic-np-6 ..........   Passed   11.05 sec
      Start 30: feelpp_qs_laplacian_3d-tetrahedron-quadratic-np-1
30/40 Test #30: feelpp_qs_laplacian_3d-tetrahedron-quadratic-np-1 ..........   Passed   26.69 sec
      Start 31: feelpp_qs_adr_2d-square-np-6
31/40 Test #31: feelpp_qs_adr_2d-square-np-6 ...............................   Passed    1.88 sec
      Start 32: feelpp_qs_adr_2d-square-np-1
32/40 Test #32: feelpp_qs_adr_2d-square-np-1 ...............................   Passed    1.95 sec
      Start 33: feelpp_qs_stokes_2d-triangle-oneelt-{x,-y}-np-6
33/40 Test #33: feelpp_qs_stokes_2d-triangle-oneelt-{x,-y}-np-6 ............   Passed    1.99 sec
      Start 34: feelpp_qs_stokes_2d-triangle-oneelt-{x,-y}-np-1
34/40 Test #34: feelpp_qs_stokes_2d-triangle-oneelt-{x,-y}-np-1 ............   Passed    2.06 sec
      Start 35: feelpp_qs_stokes_2d-triangle-{x,-y}-np-6
35/40 Test #35: feelpp_qs_stokes_2d-triangle-{x,-y}-np-6 ...................   Passed    2.92 sec
      Start 36: feelpp_qs_stokes_2d-triangle-{x,-y}-np-1
36/40 Test #36: feelpp_qs_stokes_2d-triangle-{x,-y}-np-1 ...................   Passed    2.95 sec
      Start 37: feelpp_qs_stokes_3d-tetrahedron-oneelt-{x,y,-2*z}-np-6
37/40 Test #37: feelpp_qs_stokes_3d-tetrahedron-oneelt-{x,y,-2*z}-np-6 .....   Passed   11.76 sec
      Start 38: feelpp_qs_stokes_3d-tetrahedron-oneelt-{x,y,-2*z}-np-1
38/40 Test #38: feelpp_qs_stokes_3d-tetrahedron-oneelt-{x,y,-2*z}-np-1 .....   Passed   10.38 sec
      Start 39: feelpp_qs_elasticity_2d-cantilever-np-6
39/40 Test #39: feelpp_qs_elasticity_2d-cantilever-np-6 ....................   Passed    2.92 sec
      Start 40: feelpp_qs_elasticity_2d-cantilever-np-1
40/40 Test #40: feelpp_qs_elasticity_2d-cantilever-np-1 ....................   Passed    3.23 sec

100% tests passed, 0 tests failed out of 40

Total Test time (real) = 210.97 sec

```

**Comment by prudhomm** [comment]
Note that the tests are done in Debug mode. A few things had to be fixed to get that working. I will commit all this ASAP

**Comment by prudhomm** [comment]
@vincentchabannes it seems that toolboxes are compiling fine. Quickstart and its testsuite are ok. 
remains to test the testsuite and CRB

**Comment by vincentchabannes** [comment]
@prudhomm I think there is no problem with CRB. The testsuite is almost OK, there is just a problem with test_quad_order which use the old static IM class Gauss<Simplex...>, and this class are currently broken by the new changes. If we replace by the new dynamic class PointSetQuadrature, it works. But there is also test with GaussLobato quadrature, but it's not yet implement in dymamic. And the other issue in testsuite is about multiscale quad.

**Comment by prudhomm** [comment]
Toolboxes are compiling fine in Debug mode! need to test now

**Comment by prudhomm** [comment]
@vincentchabannes feature/quad compiled entirely

**Comment by prudhomm** [comment]
@vincentchabannes have you tested the toolboxes?

**Comment by prudhomm** [comment]
@vincentchabannes it seems to me that the testsuite is fine now. What do you think?
when I rerun the failing tests, they are ok (I haven't retested eim, crb...)

**Comment by vincentchabannes** [comment]
@prudhomm feelpp_test_immultiscale doesn't work : 
```
 unknown location(0): fatal error: in "immultiscale_suite/im1d_test5": Feel::FactoryDefaultError<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Feel::IMBase<double> >::Exception: [Factory] Unknown Type : im(1,50,hypercube)
```

Also, we need to note that the mesh serialization has changed (point_type in element), so some crb/eim databases should be rebuild.

**Pull request merged**
