### PR TITLE
Requirements before resolving 1892: compute view factor for rht

### LINKED ISSUE #1908: Add code to solve heat equation as a sandbox for radiative heat transfer
- [x] add c++ code for heat equation
- [x]  add json spec for heat equation

### LINKED ISSUE #1909: add json spec for radiative heat transfer
add a json specification for RHT that will be implemented in the heat toolbox

### LINKED ISSUE #1910: add unobstructed view factor computation
in case of unobstructed planar surfaces, view factors can be computed with quadrature formulas. The diagonal of the VF matrix  is 0 since a planar surface does not see itself.

this needs #1904 to simplify integral computations

### PR DESCRIPTION
**Pull request by lberti**
It contains:
- a script "rht_several_enclosures.cpp" solving radiative heat transfer problems for several gray cavities
- three cases (rectangular cavity, triangular cavity, and cylindrical cavity) in 2d and 3d with comparisons with literature
- computation of view factors in unobstructed cavities (2d and 3d) with tests using numerical integration

it closes the following issues
- closes #1908 
- closes #1909 
- closes #1910

### CODE REVIEW

**Comment by lberti** [comment]
The current status of the branch will not resolve issue 1892. However, in order to include changes to solve the other three issues, I think that a first merge could be beneficial.

**Comment by prudhomm** [comment]
@lberti I just update the title of the PR and updated the description

**Comment by prudhomm** [comment]
I also updated the menus on the right

**Comment by lberti** [comment]
@prudhomm CI seems to fail because the `cases` folder is not found for the view factor test cases (which pass on my side). I don't understand how to solve the problem on Buildkite, as it seems to point to the right path, and the files exist in `testsuite/feelviewfactor/casas`

**Comment by lberti** [comment]
@vincentchabannes I could not understand how to solve the problem concerning the test on view factors on Buildkite

**Review by prudhomm — APPROVED** [review]

**Review by prudhomm — APPROVED** [review]

**Pull request merged**
