### PR TITLE
add option to edit json variables

### LINKED ISSUE #1122: Support changing json files from command line
currently, we cannot modify the json files once loaded into feel++, we have to modify them on disk.
to simplify blueprints development for MSO4SC, we should be able to modify json files from the command line.
We should define an option set where the user pass a key to access the value and use the `boost::property_tree` capabilities to update  the tree. (`put_child`, `put_value`...)

/cc @feelpp/mso4sc

### PR DESCRIPTION
**Pull request by jbwahl**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/feelpp/feelpp/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes?
- [x] Have you successfully run the Feel++ testsuite with your changes locally?

-----
close #1122 : 
The syntax is `--json-editions key1:value1 key2:value2`
For instance if you want to edit the value of the diffusivity `k` in https://github.com/feelpp/feelpp/blob/develop/toolboxes/hdg/mixed-poisson/test3d.json, you can add the option:`--json-editions Materials.omega.k:3`

### CODE REVIEW

**Comment by jbwahl** [comment]
The design still has to be reviewed but it works fine for now.
We can now edit the values of the variables in the json file. Only available in the material properties of the toolboxes for now.
The syntax is `--json-options key1:value1 key2:value2`
For instance if you want to edit the value of the diffusivity `k` to 3 in https://github.com/feelpp/feelpp/blob/develop/toolboxes/hdg/mixed-poisson/test3d.json, you can add the option:`--json-options Materials.omega.k:3`

**Comment by prudhomm** [comment]
Please add some tests to `testsuite/feelcore/`

**Comment by prudhomm** [comment]
@jbwahl the PR description needs to list the issues you are dealing with here

**Comment by jbwahl** [comment]
@vincentchabannes I am waiting for your feedback on the last changes 
Testsuite is running

**Comment by prudhomm** [comment]
how about `--json-edit` it is shorter than `--json-editions` ?

**Comment by vincentchabannes** [comment]
@prudhomm @jbwahl is it normal that the pull request is closed but it's not merged in develop?

**Comment by prudhomm** [comment]
Probably not

**Pull request merged**
