### PR TITLE
Feature/ensemble

### LINKED ISSUE #1825: support ensemble simulations in parallel
support ensemble simulations in parallel to accelerate the evaluations of models in eg kalman filters

if we have say N*P processes, we can split the world communicator into N sub communicators grouping P processes that can execute in parallel. It is expected that toolboxes can. be run in this context. It means that they should support subcommunicators and that we can disable printing to avoid scrambling the screen or logs. We could just enable printing for only one of the subcommunicator

### LINKED ISSUE #1826: split worldcomm in n worldcomms
splitting a worldcomm into n subworldcomm having each say p processes enables parallel methods for ensemble simulations, reinforcement learning or parameter sweeps

### LINKED ISSUE #1827: support WorldComm in norm computations other than Environment::WorldComm
norm computations should be computable on any relevant communicator not only Environment::WorldComm 
useful for #1825

### LINKED ISSUE #1828: support ini parser in python
a ini parser is useful to manipulate easily options

@Trophime I used config parser and I add a section `feelpp` for section-less options

### LINKED ISSUE #1829: support toolbox worldcomm in statistics/measures computations
measures and statistics use Environment:worldCommPtr() instead of the toolbox. It then forbids #1825 or have a specific communicator for a toolbox

### PR DESCRIPTION
**Pull request by prudhomm**
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/feelpp/feelpp/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes?
- [ ] Have you successfully run the Feel++ testsuite with your changes locally?
- [ ] Have you written Doxygen comments in your contribution ?

-----
- fixes #1825
- fixes #1826 
- fixes #1827 
- fixes #1828
- fixes #1829

### CODE REVIEW

**Comment by prudhomm** [comment]
@lberti @VLCeline @zakaryael we should now be able to do RL in parallel

@lberti idem for ensemble simulations

**Comment by prudhomm** [comment]
@vincentchabannes I added some code to tests the toolbox in // in `toolboxes/tests/heat/test_heat.cpp`

**Comment by vincentchabannes** [comment]
@prudhomm I think really that is not a good way to fix the communicator issue. And there are other locations where the comm will be wrong. If we implement #1489, changes will be only in feelpp, not in toolboxes, and fix all parts. Take more time but impact clearly larger

**Comment by prudhomm** [comment]
Ok i will try to do that

**Comment by vincentchabannes** [comment]
Moreover, I have planned to not apply mpi reduce when computing each measure, but only one mpi comm when all local measures will be stored

**Comment by vincentchabannes** [comment]
@prudhomm  for the struct with range, the idea is to store also the MeshBase object inside (even if the range is empty on a process). So we will access some useful info as WorldComm, markers... .

**Pull request closed without merging**
